//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCongel.Reservations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", ConfigurationName="Reservations.Reservations_Port")]
    public interface Reservations_Port {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Read_Result) du message Read_Result ne correspond pas à la valeur par défaut (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.Read_Result Read(ScanCongel.Reservations.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Read_Result> ReadAsync(ScanCongel.Reservations.Read request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadByRecId_Result) du message ReadByRecId_Result ne correspond pas à la valeur par défaut (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.ReadByRecId_Result ReadByRecId(ScanCongel.Reservations.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.ReadByRecId_Result> ReadByRecIdAsync(ScanCongel.Reservations.ReadByRecId request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadMultiple_Result) du message ReadMultiple_Result ne correspond pas à la valeur par défaut (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.ReadMultiple_Result ReadMultiple(ScanCongel.Reservations.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.Reservations.ReadMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (IsUpdated_Result) du message IsUpdated_Result ne correspond pas à la valeur par défaut (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.IsUpdated_Result IsUpdated(ScanCongel.Reservations.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.IsUpdated_Result> IsUpdatedAsync(ScanCongel.Reservations.IsUpdated request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (GetRecIdFromKey_Result) du message GetRecIdFromKey_Result ne correspond pas à la valeur par défaut (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.GetRecIdFromKey_Result GetRecIdFromKey(ScanCongel.Reservations.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ScanCongel.Reservations.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.Create_Result Create(ScanCongel.Reservations.Create request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Create_Result> CreateAsync(ScanCongel.Reservations.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.CreateMultiple_Result CreateMultiple(ScanCongel.Reservations.CreateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.Reservations.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.Update_Result Update(ScanCongel.Reservations.Update request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Update_Result> UpdateAsync(ScanCongel.Reservations.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.UpdateMultiple_Result UpdateMultiple(ScanCongel.Reservations.UpdateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.Reservations.UpdateMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Delete_Result) du message Delete_Result ne correspond pas à la valeur par défaut (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.Reservations.Delete_Result Delete(ScanCongel.Reservations.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservations:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Delete_Result> DeleteAsync(ScanCongel.Reservations.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public partial class Reservations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private string item_NoField;
        
        private string location_CodeField;
        
        private decimal quantity_BaseField;
        
        private bool quantity_BaseFieldSpecified;
        
        private Reservation_Status reservation_StatusField;
        
        private bool reservation_StatusFieldSpecified;
        
        private string descriptionField;
        
        private System.DateTime creation_DateField;
        
        private bool creation_DateFieldSpecified;
        
        private int transferred_from_Entry_NoField;
        
        private bool transferred_from_Entry_NoFieldSpecified;
        
        private int source_TypeField;
        
        private bool source_TypeFieldSpecified;
        
        private Source_Subtype source_SubtypeField;
        
        private bool source_SubtypeFieldSpecified;
        
        private string source_IDField;
        
        private string source_Batch_NameField;
        
        private int source_Prod_Order_LineField;
        
        private bool source_Prod_Order_LineFieldSpecified;
        
        private int source_Ref_NoField;
        
        private bool source_Ref_NoFieldSpecified;
        
        private int appl_to_Item_EntryField;
        
        private bool appl_to_Item_EntryFieldSpecified;
        
        private System.DateTime expected_Receipt_DateField;
        
        private bool expected_Receipt_DateFieldSpecified;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private string serial_NoField;
        
        private string created_ByField;
        
        private string changed_ByField;
        
        private bool positiveField;
        
        private bool positiveFieldSpecified;
        
        private decimal qty_per_Unit_of_MeasureField;
        
        private bool qty_per_Unit_of_MeasureFieldSpecified;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal action_Message_AdjustmentField;
        
        private bool action_Message_AdjustmentFieldSpecified;
        
        private Binding bindingField;
        
        private bool bindingFieldSpecified;
        
        private bool suppressed_Action_MsgField;
        
        private bool suppressed_Action_MsgFieldSpecified;
        
        private Planning_Flexibility planning_FlexibilityField;
        
        private bool planning_FlexibilityFieldSpecified;
        
        private System.DateTime warranty_DateField;
        
        private bool warranty_DateFieldSpecified;
        
        private System.DateTime expiration_DateField;
        
        private bool expiration_DateFieldSpecified;
        
        private decimal qty_to_Handle_BaseField;
        
        private bool qty_to_Handle_BaseFieldSpecified;
        
        private decimal qty_to_Invoice_BaseField;
        
        private bool qty_to_Invoice_BaseFieldSpecified;
        
        private decimal quantity_Invoiced_BaseField;
        
        private bool quantity_Invoiced_BaseFieldSpecified;
        
        private decimal reserved_Pick__Ship_QtyField;
        
        private bool reserved_Pick__Ship_QtyFieldSpecified;
        
        private string new_Serial_NoField;
        
        private string new_Lot_NoField;
        
        private string lot_NoField;
        
        private string variant_CodeField;
        
        private int appl_from_Item_EntryField;
        
        private bool appl_from_Item_EntryFieldSpecified;
        
        private bool correctionField;
        
        private bool correctionFieldSpecified;
        
        private System.DateTime new_Expiration_DateField;
        
        private bool new_Expiration_DateFieldSpecified;
        
        private Item_Tracking item_TrackingField;
        
        private bool item_TrackingFieldSpecified;
        
        private int pallet_QtyField;
        
        private bool pallet_QtyFieldSpecified;
        
        private decimal qty_To_TreatField;
        
        private bool qty_To_TreatFieldSpecified;
        
        private int pallet_Qty_to_TreatField;
        
        private bool pallet_Qty_to_TreatFieldSpecified;
        
        private string bin_CodeField;
        
        private bool add_on_existing_palletField;
        
        private bool add_on_existing_palletFieldSpecified;
        
        private string item_Jnl_Bin_CodeField;
        
        private string first_bin_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Entry_No {
            get {
                return this.entry_NoField;
            }
            set {
                this.entry_NoField = value;
                this.RaisePropertyChanged("Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified {
            get {
                return this.entry_NoFieldSpecified;
            }
            set {
                this.entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Item_No {
            get {
                return this.item_NoField;
            }
            set {
                this.item_NoField = value;
                this.RaisePropertyChanged("Item_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Quantity_Base {
            get {
                return this.quantity_BaseField;
            }
            set {
                this.quantity_BaseField = value;
                this.RaisePropertyChanged("Quantity_Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_BaseSpecified {
            get {
                return this.quantity_BaseFieldSpecified;
            }
            set {
                this.quantity_BaseFieldSpecified = value;
                this.RaisePropertyChanged("Quantity_BaseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Reservation_Status Reservation_Status {
            get {
                return this.reservation_StatusField;
            }
            set {
                this.reservation_StatusField = value;
                this.RaisePropertyChanged("Reservation_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reservation_StatusSpecified {
            get {
                return this.reservation_StatusFieldSpecified;
            }
            set {
                this.reservation_StatusFieldSpecified = value;
                this.RaisePropertyChanged("Reservation_StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
                this.RaisePropertyChanged("Creation_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_DateSpecified {
            get {
                return this.creation_DateFieldSpecified;
            }
            set {
                this.creation_DateFieldSpecified = value;
                this.RaisePropertyChanged("Creation_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Transferred_from_Entry_No {
            get {
                return this.transferred_from_Entry_NoField;
            }
            set {
                this.transferred_from_Entry_NoField = value;
                this.RaisePropertyChanged("Transferred_from_Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transferred_from_Entry_NoSpecified {
            get {
                return this.transferred_from_Entry_NoFieldSpecified;
            }
            set {
                this.transferred_from_Entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Transferred_from_Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Source_Type {
            get {
                return this.source_TypeField;
            }
            set {
                this.source_TypeField = value;
                this.RaisePropertyChanged("Source_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_TypeSpecified {
            get {
                return this.source_TypeFieldSpecified;
            }
            set {
                this.source_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Source_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Source_Subtype Source_Subtype {
            get {
                return this.source_SubtypeField;
            }
            set {
                this.source_SubtypeField = value;
                this.RaisePropertyChanged("Source_Subtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_SubtypeSpecified {
            get {
                return this.source_SubtypeFieldSpecified;
            }
            set {
                this.source_SubtypeFieldSpecified = value;
                this.RaisePropertyChanged("Source_SubtypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Source_ID {
            get {
                return this.source_IDField;
            }
            set {
                this.source_IDField = value;
                this.RaisePropertyChanged("Source_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Source_Batch_Name {
            get {
                return this.source_Batch_NameField;
            }
            set {
                this.source_Batch_NameField = value;
                this.RaisePropertyChanged("Source_Batch_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Source_Prod_Order_Line {
            get {
                return this.source_Prod_Order_LineField;
            }
            set {
                this.source_Prod_Order_LineField = value;
                this.RaisePropertyChanged("Source_Prod_Order_Line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_Prod_Order_LineSpecified {
            get {
                return this.source_Prod_Order_LineFieldSpecified;
            }
            set {
                this.source_Prod_Order_LineFieldSpecified = value;
                this.RaisePropertyChanged("Source_Prod_Order_LineSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Source_Ref_No {
            get {
                return this.source_Ref_NoField;
            }
            set {
                this.source_Ref_NoField = value;
                this.RaisePropertyChanged("Source_Ref_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Source_Ref_NoSpecified {
            get {
                return this.source_Ref_NoFieldSpecified;
            }
            set {
                this.source_Ref_NoFieldSpecified = value;
                this.RaisePropertyChanged("Source_Ref_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Appl_to_Item_Entry {
            get {
                return this.appl_to_Item_EntryField;
            }
            set {
                this.appl_to_Item_EntryField = value;
                this.RaisePropertyChanged("Appl_to_Item_Entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appl_to_Item_EntrySpecified {
            get {
                return this.appl_to_Item_EntryFieldSpecified;
            }
            set {
                this.appl_to_Item_EntryFieldSpecified = value;
                this.RaisePropertyChanged("Appl_to_Item_EntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime Expected_Receipt_Date {
            get {
                return this.expected_Receipt_DateField;
            }
            set {
                this.expected_Receipt_DateField = value;
                this.RaisePropertyChanged("Expected_Receipt_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expected_Receipt_DateSpecified {
            get {
                return this.expected_Receipt_DateFieldSpecified;
            }
            set {
                this.expected_Receipt_DateFieldSpecified = value;
                this.RaisePropertyChanged("Expected_Receipt_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
                this.RaisePropertyChanged("Shipment_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
                this.RaisePropertyChanged("Shipment_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Serial_No {
            get {
                return this.serial_NoField;
            }
            set {
                this.serial_NoField = value;
                this.RaisePropertyChanged("Serial_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Created_By {
            get {
                return this.created_ByField;
            }
            set {
                this.created_ByField = value;
                this.RaisePropertyChanged("Created_By");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Changed_By {
            get {
                return this.changed_ByField;
            }
            set {
                this.changed_ByField = value;
                this.RaisePropertyChanged("Changed_By");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Positive {
            get {
                return this.positiveField;
            }
            set {
                this.positiveField = value;
                this.RaisePropertyChanged("Positive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PositiveSpecified {
            get {
                return this.positiveFieldSpecified;
            }
            set {
                this.positiveFieldSpecified = value;
                this.RaisePropertyChanged("PositiveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Qty_per_Unit_of_Measure {
            get {
                return this.qty_per_Unit_of_MeasureField;
            }
            set {
                this.qty_per_Unit_of_MeasureField = value;
                this.RaisePropertyChanged("Qty_per_Unit_of_Measure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_per_Unit_of_MeasureSpecified {
            get {
                return this.qty_per_Unit_of_MeasureFieldSpecified;
            }
            set {
                this.qty_per_Unit_of_MeasureFieldSpecified = value;
                this.RaisePropertyChanged("Qty_per_Unit_of_MeasureSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Action_Message_Adjustment {
            get {
                return this.action_Message_AdjustmentField;
            }
            set {
                this.action_Message_AdjustmentField = value;
                this.RaisePropertyChanged("Action_Message_Adjustment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Action_Message_AdjustmentSpecified {
            get {
                return this.action_Message_AdjustmentFieldSpecified;
            }
            set {
                this.action_Message_AdjustmentFieldSpecified = value;
                this.RaisePropertyChanged("Action_Message_AdjustmentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public Binding Binding {
            get {
                return this.bindingField;
            }
            set {
                this.bindingField = value;
                this.RaisePropertyChanged("Binding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BindingSpecified {
            get {
                return this.bindingFieldSpecified;
            }
            set {
                this.bindingFieldSpecified = value;
                this.RaisePropertyChanged("BindingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool Suppressed_Action_Msg {
            get {
                return this.suppressed_Action_MsgField;
            }
            set {
                this.suppressed_Action_MsgField = value;
                this.RaisePropertyChanged("Suppressed_Action_Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Suppressed_Action_MsgSpecified {
            get {
                return this.suppressed_Action_MsgFieldSpecified;
            }
            set {
                this.suppressed_Action_MsgFieldSpecified = value;
                this.RaisePropertyChanged("Suppressed_Action_MsgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public Planning_Flexibility Planning_Flexibility {
            get {
                return this.planning_FlexibilityField;
            }
            set {
                this.planning_FlexibilityField = value;
                this.RaisePropertyChanged("Planning_Flexibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Planning_FlexibilitySpecified {
            get {
                return this.planning_FlexibilityFieldSpecified;
            }
            set {
                this.planning_FlexibilityFieldSpecified = value;
                this.RaisePropertyChanged("Planning_FlexibilitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=28)]
        public System.DateTime Warranty_Date {
            get {
                return this.warranty_DateField;
            }
            set {
                this.warranty_DateField = value;
                this.RaisePropertyChanged("Warranty_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Warranty_DateSpecified {
            get {
                return this.warranty_DateFieldSpecified;
            }
            set {
                this.warranty_DateFieldSpecified = value;
                this.RaisePropertyChanged("Warranty_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=29)]
        public System.DateTime Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
                this.RaisePropertyChanged("Expiration_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Expiration_DateSpecified {
            get {
                return this.expiration_DateFieldSpecified;
            }
            set {
                this.expiration_DateFieldSpecified = value;
                this.RaisePropertyChanged("Expiration_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal Qty_to_Handle_Base {
            get {
                return this.qty_to_Handle_BaseField;
            }
            set {
                this.qty_to_Handle_BaseField = value;
                this.RaisePropertyChanged("Qty_to_Handle_Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_Handle_BaseSpecified {
            get {
                return this.qty_to_Handle_BaseFieldSpecified;
            }
            set {
                this.qty_to_Handle_BaseFieldSpecified = value;
                this.RaisePropertyChanged("Qty_to_Handle_BaseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal Qty_to_Invoice_Base {
            get {
                return this.qty_to_Invoice_BaseField;
            }
            set {
                this.qty_to_Invoice_BaseField = value;
                this.RaisePropertyChanged("Qty_to_Invoice_Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_Invoice_BaseSpecified {
            get {
                return this.qty_to_Invoice_BaseFieldSpecified;
            }
            set {
                this.qty_to_Invoice_BaseFieldSpecified = value;
                this.RaisePropertyChanged("Qty_to_Invoice_BaseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal Quantity_Invoiced_Base {
            get {
                return this.quantity_Invoiced_BaseField;
            }
            set {
                this.quantity_Invoiced_BaseField = value;
                this.RaisePropertyChanged("Quantity_Invoiced_Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_Invoiced_BaseSpecified {
            get {
                return this.quantity_Invoiced_BaseFieldSpecified;
            }
            set {
                this.quantity_Invoiced_BaseFieldSpecified = value;
                this.RaisePropertyChanged("Quantity_Invoiced_BaseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reserved_Pick_&_Ship_Qty", Order=33)]
        public decimal Reserved_Pick__Ship_Qty {
            get {
                return this.reserved_Pick__Ship_QtyField;
            }
            set {
                this.reserved_Pick__Ship_QtyField = value;
                this.RaisePropertyChanged("Reserved_Pick__Ship_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reserved_Pick__Ship_QtySpecified {
            get {
                return this.reserved_Pick__Ship_QtyFieldSpecified;
            }
            set {
                this.reserved_Pick__Ship_QtyFieldSpecified = value;
                this.RaisePropertyChanged("Reserved_Pick__Ship_QtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string New_Serial_No {
            get {
                return this.new_Serial_NoField;
            }
            set {
                this.new_Serial_NoField = value;
                this.RaisePropertyChanged("New_Serial_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string New_Lot_No {
            get {
                return this.new_Lot_NoField;
            }
            set {
                this.new_Lot_NoField = value;
                this.RaisePropertyChanged("New_Lot_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Lot_No {
            get {
                return this.lot_NoField;
            }
            set {
                this.lot_NoField = value;
                this.RaisePropertyChanged("Lot_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
                this.RaisePropertyChanged("Variant_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int Appl_from_Item_Entry {
            get {
                return this.appl_from_Item_EntryField;
            }
            set {
                this.appl_from_Item_EntryField = value;
                this.RaisePropertyChanged("Appl_from_Item_Entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appl_from_Item_EntrySpecified {
            get {
                return this.appl_from_Item_EntryFieldSpecified;
            }
            set {
                this.appl_from_Item_EntryFieldSpecified = value;
                this.RaisePropertyChanged("Appl_from_Item_EntrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool Correction {
            get {
                return this.correctionField;
            }
            set {
                this.correctionField = value;
                this.RaisePropertyChanged("Correction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CorrectionSpecified {
            get {
                return this.correctionFieldSpecified;
            }
            set {
                this.correctionFieldSpecified = value;
                this.RaisePropertyChanged("CorrectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=40)]
        public System.DateTime New_Expiration_Date {
            get {
                return this.new_Expiration_DateField;
            }
            set {
                this.new_Expiration_DateField = value;
                this.RaisePropertyChanged("New_Expiration_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool New_Expiration_DateSpecified {
            get {
                return this.new_Expiration_DateFieldSpecified;
            }
            set {
                this.new_Expiration_DateFieldSpecified = value;
                this.RaisePropertyChanged("New_Expiration_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public Item_Tracking Item_Tracking {
            get {
                return this.item_TrackingField;
            }
            set {
                this.item_TrackingField = value;
                this.RaisePropertyChanged("Item_Tracking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item_TrackingSpecified {
            get {
                return this.item_TrackingFieldSpecified;
            }
            set {
                this.item_TrackingFieldSpecified = value;
                this.RaisePropertyChanged("Item_TrackingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int Pallet_Qty {
            get {
                return this.pallet_QtyField;
            }
            set {
                this.pallet_QtyField = value;
                this.RaisePropertyChanged("Pallet_Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pallet_QtySpecified {
            get {
                return this.pallet_QtyFieldSpecified;
            }
            set {
                this.pallet_QtyFieldSpecified = value;
                this.RaisePropertyChanged("Pallet_QtySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public decimal Qty_To_Treat {
            get {
                return this.qty_To_TreatField;
            }
            set {
                this.qty_To_TreatField = value;
                this.RaisePropertyChanged("Qty_To_Treat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_To_TreatSpecified {
            get {
                return this.qty_To_TreatFieldSpecified;
            }
            set {
                this.qty_To_TreatFieldSpecified = value;
                this.RaisePropertyChanged("Qty_To_TreatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public int Pallet_Qty_to_Treat {
            get {
                return this.pallet_Qty_to_TreatField;
            }
            set {
                this.pallet_Qty_to_TreatField = value;
                this.RaisePropertyChanged("Pallet_Qty_to_Treat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pallet_Qty_to_TreatSpecified {
            get {
                return this.pallet_Qty_to_TreatFieldSpecified;
            }
            set {
                this.pallet_Qty_to_TreatFieldSpecified = value;
                this.RaisePropertyChanged("Pallet_Qty_to_TreatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
                this.RaisePropertyChanged("Bin_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool Add_on_existing_pallet {
            get {
                return this.add_on_existing_palletField;
            }
            set {
                this.add_on_existing_palletField = value;
                this.RaisePropertyChanged("Add_on_existing_pallet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Add_on_existing_palletSpecified {
            get {
                return this.add_on_existing_palletFieldSpecified;
            }
            set {
                this.add_on_existing_palletFieldSpecified = value;
                this.RaisePropertyChanged("Add_on_existing_palletSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string Item_Jnl_Bin_Code {
            get {
                return this.item_Jnl_Bin_CodeField;
            }
            set {
                this.item_Jnl_Bin_CodeField = value;
                this.RaisePropertyChanged("Item_Jnl_Bin_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string First_bin_code {
            get {
                return this.first_bin_codeField;
            }
            set {
                this.first_bin_codeField = value;
                this.RaisePropertyChanged("First_bin_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Reservation_Status {
        
        /// <remarks/>
        Reservation,
        
        /// <remarks/>
        Tracking,
        
        /// <remarks/>
        Surplus,
        
        /// <remarks/>
        Prospect,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Source_Subtype {
        
        /// <remarks/>
        _x0030_,
        
        /// <remarks/>
        _x0031_,
        
        /// <remarks/>
        _x0032_,
        
        /// <remarks/>
        _x0033_,
        
        /// <remarks/>
        _x0034_,
        
        /// <remarks/>
        _x0035_,
        
        /// <remarks/>
        _x0036_,
        
        /// <remarks/>
        _x0037_,
        
        /// <remarks/>
        _x0038_,
        
        /// <remarks/>
        _x0039_,
        
        /// <remarks/>
        _x0031_0,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Binding {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Order_to_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Planning_Flexibility {
        
        /// <remarks/>
        Unlimited,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Item_Tracking {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Lot_No,
        
        /// <remarks/>
        Lot_and_Serial_No,
        
        /// <remarks/>
        Serial_No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public partial class Reservations_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Reservations_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Reservations_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations")]
    public enum Reservations_Fields {
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        Item_No,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Quantity_Base,
        
        /// <remarks/>
        Reservation_Status,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Creation_Date,
        
        /// <remarks/>
        Transferred_from_Entry_No,
        
        /// <remarks/>
        Source_Type,
        
        /// <remarks/>
        Source_Subtype,
        
        /// <remarks/>
        Source_ID,
        
        /// <remarks/>
        Source_Batch_Name,
        
        /// <remarks/>
        Source_Prod_Order_Line,
        
        /// <remarks/>
        Source_Ref_No,
        
        /// <remarks/>
        Appl_to_Item_Entry,
        
        /// <remarks/>
        Expected_Receipt_Date,
        
        /// <remarks/>
        Shipment_Date,
        
        /// <remarks/>
        Serial_No,
        
        /// <remarks/>
        Created_By,
        
        /// <remarks/>
        Changed_By,
        
        /// <remarks/>
        Positive,
        
        /// <remarks/>
        Qty_per_Unit_of_Measure,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Action_Message_Adjustment,
        
        /// <remarks/>
        Binding,
        
        /// <remarks/>
        Suppressed_Action_Msg,
        
        /// <remarks/>
        Planning_Flexibility,
        
        /// <remarks/>
        Warranty_Date,
        
        /// <remarks/>
        Expiration_Date,
        
        /// <remarks/>
        Qty_to_Handle_Base,
        
        /// <remarks/>
        Qty_to_Invoice_Base,
        
        /// <remarks/>
        Quantity_Invoiced_Base,
        
        /// <remarks/>
        Reserved_Pick__x0026__Ship_Qty,
        
        /// <remarks/>
        New_Serial_No,
        
        /// <remarks/>
        New_Lot_No,
        
        /// <remarks/>
        Lot_No,
        
        /// <remarks/>
        Variant_Code,
        
        /// <remarks/>
        Appl_from_Item_Entry,
        
        /// <remarks/>
        Correction,
        
        /// <remarks/>
        New_Expiration_Date,
        
        /// <remarks/>
        Item_Tracking,
        
        /// <remarks/>
        Pallet_Qty,
        
        /// <remarks/>
        Qty_To_Treat,
        
        /// <remarks/>
        Pallet_Qty_to_Treat,
        
        /// <remarks/>
        Bin_Code,
        
        /// <remarks/>
        Add_on_existing_pallet,
        
        /// <remarks/>
        Item_Jnl_Bin_Code,
        
        /// <remarks/>
        First_bin_code,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public int Entry_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=1)]
        public bool Positive;
        
        public Read() {
        }
        
        public Read(int Entry_No, bool Positive) {
            this.Entry_No = Entry_No;
            this.Positive = Positive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public Read_Result() {
        }
        
        public Read_Result(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ScanCongel.Reservations.Reservations_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ScanCongel.Reservations.Reservations_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.Reservations.Reservations[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ScanCongel.Reservations.Reservations[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public Create() {
        }
        
        public Create(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public Create_Result() {
        }
        
        public Create_Result(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.Reservations.Reservations[] Reservations_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ScanCongel.Reservations.Reservations[] Reservations_List) {
            this.Reservations_List = Reservations_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.Reservations.Reservations[] Reservations_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ScanCongel.Reservations.Reservations[] Reservations_List) {
            this.Reservations_List = Reservations_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public Update() {
        }
        
        public Update(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public ScanCongel.Reservations.Reservations Reservations;
        
        public Update_Result() {
        }
        
        public Update_Result(ScanCongel.Reservations.Reservations Reservations) {
            this.Reservations = Reservations;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.Reservations.Reservations[] Reservations_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ScanCongel.Reservations.Reservations[] Reservations_List) {
            this.Reservations_List = Reservations_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.Reservations.Reservations[] Reservations_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ScanCongel.Reservations.Reservations[] Reservations_List) {
            this.Reservations_List = Reservations_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservations", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservations", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Reservations_PortChannel : ScanCongel.Reservations.Reservations_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Reservations_PortClient : System.ServiceModel.ClientBase<ScanCongel.Reservations.Reservations_Port>, ScanCongel.Reservations.Reservations_Port {
        
        public Reservations_PortClient() {
        }
        
        public Reservations_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Reservations_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Reservations_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Reservations_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.Read_Result ScanCongel.Reservations.Reservations_Port.Read(ScanCongel.Reservations.Read request) {
            return base.Channel.Read(request);
        }
        
        public ScanCongel.Reservations.Reservations Read(int Entry_No, bool Positive) {
            ScanCongel.Reservations.Read inValue = new ScanCongel.Reservations.Read();
            inValue.Entry_No = Entry_No;
            inValue.Positive = Positive;
            ScanCongel.Reservations.Read_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).Read(inValue);
            return retVal.Reservations;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Read_Result> ScanCongel.Reservations.Reservations_Port.ReadAsync(ScanCongel.Reservations.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.Read_Result> ReadAsync(int Entry_No, bool Positive) {
            ScanCongel.Reservations.Read inValue = new ScanCongel.Reservations.Read();
            inValue.Entry_No = Entry_No;
            inValue.Positive = Positive;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.ReadByRecId_Result ScanCongel.Reservations.Reservations_Port.ReadByRecId(ScanCongel.Reservations.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ScanCongel.Reservations.Reservations ReadByRecId(string recId) {
            ScanCongel.Reservations.ReadByRecId inValue = new ScanCongel.Reservations.ReadByRecId();
            inValue.recId = recId;
            ScanCongel.Reservations.ReadByRecId_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).ReadByRecId(inValue);
            return retVal.Reservations;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.ReadByRecId_Result> ScanCongel.Reservations.Reservations_Port.ReadByRecIdAsync(ScanCongel.Reservations.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ScanCongel.Reservations.ReadByRecId inValue = new ScanCongel.Reservations.ReadByRecId();
            inValue.recId = recId;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.ReadMultiple_Result ScanCongel.Reservations.Reservations_Port.ReadMultiple(ScanCongel.Reservations.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ScanCongel.Reservations.Reservations[] ReadMultiple(ScanCongel.Reservations.Reservations_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.Reservations.ReadMultiple inValue = new ScanCongel.Reservations.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ScanCongel.Reservations.ReadMultiple_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.ReadMultiple_Result> ScanCongel.Reservations.Reservations_Port.ReadMultipleAsync(ScanCongel.Reservations.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.Reservations.Reservations_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.Reservations.ReadMultiple inValue = new ScanCongel.Reservations.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.IsUpdated_Result ScanCongel.Reservations.Reservations_Port.IsUpdated(ScanCongel.Reservations.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ScanCongel.Reservations.IsUpdated inValue = new ScanCongel.Reservations.IsUpdated();
            inValue.Key = Key;
            ScanCongel.Reservations.IsUpdated_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.IsUpdated_Result> ScanCongel.Reservations.Reservations_Port.IsUpdatedAsync(ScanCongel.Reservations.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ScanCongel.Reservations.IsUpdated inValue = new ScanCongel.Reservations.IsUpdated();
            inValue.Key = Key;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.GetRecIdFromKey_Result ScanCongel.Reservations.Reservations_Port.GetRecIdFromKey(ScanCongel.Reservations.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ScanCongel.Reservations.GetRecIdFromKey inValue = new ScanCongel.Reservations.GetRecIdFromKey();
            inValue.Key = Key;
            ScanCongel.Reservations.GetRecIdFromKey_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.GetRecIdFromKey_Result> ScanCongel.Reservations.Reservations_Port.GetRecIdFromKeyAsync(ScanCongel.Reservations.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ScanCongel.Reservations.GetRecIdFromKey inValue = new ScanCongel.Reservations.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.Create_Result ScanCongel.Reservations.Reservations_Port.Create(ScanCongel.Reservations.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ScanCongel.Reservations.Reservations Reservations) {
            ScanCongel.Reservations.Create inValue = new ScanCongel.Reservations.Create();
            inValue.Reservations = Reservations;
            ScanCongel.Reservations.Create_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).Create(inValue);
            Reservations = retVal.Reservations;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.Create_Result> CreateAsync(ScanCongel.Reservations.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.CreateMultiple_Result ScanCongel.Reservations.Reservations_Port.CreateMultiple(ScanCongel.Reservations.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ScanCongel.Reservations.Reservations[] Reservations_List) {
            ScanCongel.Reservations.CreateMultiple inValue = new ScanCongel.Reservations.CreateMultiple();
            inValue.Reservations_List = Reservations_List;
            ScanCongel.Reservations.CreateMultiple_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).CreateMultiple(inValue);
            Reservations_List = retVal.Reservations_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.Reservations.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.Update_Result ScanCongel.Reservations.Reservations_Port.Update(ScanCongel.Reservations.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ScanCongel.Reservations.Reservations Reservations) {
            ScanCongel.Reservations.Update inValue = new ScanCongel.Reservations.Update();
            inValue.Reservations = Reservations;
            ScanCongel.Reservations.Update_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).Update(inValue);
            Reservations = retVal.Reservations;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.Update_Result> UpdateAsync(ScanCongel.Reservations.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.UpdateMultiple_Result ScanCongel.Reservations.Reservations_Port.UpdateMultiple(ScanCongel.Reservations.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ScanCongel.Reservations.Reservations[] Reservations_List) {
            ScanCongel.Reservations.UpdateMultiple inValue = new ScanCongel.Reservations.UpdateMultiple();
            inValue.Reservations_List = Reservations_List;
            ScanCongel.Reservations.UpdateMultiple_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).UpdateMultiple(inValue);
            Reservations_List = retVal.Reservations_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.Reservations.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.Reservations.Delete_Result ScanCongel.Reservations.Reservations_Port.Delete(ScanCongel.Reservations.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ScanCongel.Reservations.Delete inValue = new ScanCongel.Reservations.Delete();
            inValue.Key = Key;
            ScanCongel.Reservations.Delete_Result retVal = ((ScanCongel.Reservations.Reservations_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.Reservations.Delete_Result> ScanCongel.Reservations.Reservations_Port.DeleteAsync(ScanCongel.Reservations.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.Reservations.Delete_Result> DeleteAsync(string Key) {
            ScanCongel.Reservations.Delete inValue = new ScanCongel.Reservations.Delete();
            inValue.Key = Key;
            return ((ScanCongel.Reservations.Reservations_Port)(this)).DeleteAsync(inValue);
        }
    }
}
