//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCongel.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", ConfigurationName="ServiceReference1.Pallets_Port")]
    public interface Pallets_Port {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Read_Result) du message Read_Result ne correspond pas à la valeur par défaut (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.Read_Result Read(ScanCongel.ServiceReference1.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Read_Result> ReadAsync(ScanCongel.ServiceReference1.Read request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadByRecId_Result) du message ReadByRecId_Result ne correspond pas à la valeur par défaut (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.ReadByRecId_Result ReadByRecId(ScanCongel.ServiceReference1.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(ScanCongel.ServiceReference1.ReadByRecId request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadMultiple_Result) du message ReadMultiple_Result ne correspond pas à la valeur par défaut (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.ReadMultiple_Result ReadMultiple(ScanCongel.ServiceReference1.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.ServiceReference1.ReadMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (IsUpdated_Result) du message IsUpdated_Result ne correspond pas à la valeur par défaut (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.IsUpdated_Result IsUpdated(ScanCongel.ServiceReference1.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.IsUpdated_Result> IsUpdatedAsync(ScanCongel.ServiceReference1.IsUpdated request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (GetRecIdFromKey_Result) du message GetRecIdFromKey_Result ne correspond pas à la valeur par défaut (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.GetRecIdFromKey_Result GetRecIdFromKey(ScanCongel.ServiceReference1.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ScanCongel.ServiceReference1.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.Create_Result Create(ScanCongel.ServiceReference1.Create request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Create_Result> CreateAsync(ScanCongel.ServiceReference1.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.CreateMultiple_Result CreateMultiple(ScanCongel.ServiceReference1.CreateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.ServiceReference1.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.Update_Result Update(ScanCongel.ServiceReference1.Update request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Update_Result> UpdateAsync(ScanCongel.ServiceReference1.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.UpdateMultiple_Result UpdateMultiple(ScanCongel.ServiceReference1.UpdateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.ServiceReference1.UpdateMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Delete_Result) du message Delete_Result ne correspond pas à la valeur par défaut (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ServiceReference1.Delete_Result Delete(ScanCongel.ServiceReference1.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pallets:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Delete_Result> DeleteAsync(ScanCongel.ServiceReference1.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets")]
    public partial class Pallets : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string sSCC_NoField;
        
        private string location_codeField;
        
        private decimal current_QuantityField;
        
        private bool current_QuantityFieldSpecified;
        
        private decimal current_WeightField;
        
        private bool current_WeightFieldSpecified;
        
        private Inbound_Document_Type inbound_Document_TypeField;
        
        private bool inbound_Document_TypeFieldSpecified;
        
        private string inbound_Document_NoField;
        
        private int inbound_Doc_Line_NoField;
        
        private bool inbound_Doc_Line_NoFieldSpecified;
        
        private Outbound_Document_Type outbound_Document_TypeField;
        
        private bool outbound_Document_TypeFieldSpecified;
        
        private string outbound_Document_NoField;
        
        private int outbound_Doc_Line_NoField;
        
        private bool outbound_Doc_Line_NoFieldSpecified;
        
        private int last_Entry_NoField;
        
        private bool last_Entry_NoFieldSpecified;
        
        private bool pallet_Journal_Line_ExistField;
        
        private bool pallet_Journal_Line_ExistFieldSpecified;
        
        private decimal qty_on_pallet_JnlField;
        
        private bool qty_on_pallet_JnlFieldSpecified;
        
        private System.DateTime creation_DateField;
        
        private bool creation_DateFieldSpecified;
        
        private System.DateTime creation_TimeField;
        
        private bool creation_TimeFieldSpecified;
        
        private string no_SeriesField;
        
        private string bin_codeField;
        
        private string item_NoField;
        
        private string lot_NoField;
        
        private System.DateTime dLCField;
        
        private bool dLCFieldSpecified;
        
        private int display_orderField;
        
        private bool display_orderFieldSpecified;
        
        private string item_DescriptionField;
        
        private int nbre_bacs_receptionField;
        
        private bool nbre_bacs_receptionFieldSpecified;
        
        private string type_bacs_receptionField;
        
        private string type_palette_receptionField;
        
        private int temperature_receptionField;
        
        private bool temperature_receptionFieldSpecified;
        
        private decimal poids_brut_receptionField;
        
        private bool poids_brut_receptionFieldSpecified;
        
        private string quai_receptionField;
        
        private string user_receptionField;
        
        private bool lot_bloqueField;
        
        private bool lot_bloqueFieldSpecified;
        
        private decimal quantite_receptionField;
        
        private bool quantite_receptionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SSCC_No {
            get {
                return this.sSCC_NoField;
            }
            set {
                this.sSCC_NoField = value;
                this.RaisePropertyChanged("SSCC_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Location_code {
            get {
                return this.location_codeField;
            }
            set {
                this.location_codeField = value;
                this.RaisePropertyChanged("Location_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Current_Quantity {
            get {
                return this.current_QuantityField;
            }
            set {
                this.current_QuantityField = value;
                this.RaisePropertyChanged("Current_Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Current_QuantitySpecified {
            get {
                return this.current_QuantityFieldSpecified;
            }
            set {
                this.current_QuantityFieldSpecified = value;
                this.RaisePropertyChanged("Current_QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Current_Weight {
            get {
                return this.current_WeightField;
            }
            set {
                this.current_WeightField = value;
                this.RaisePropertyChanged("Current_Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Current_WeightSpecified {
            get {
                return this.current_WeightFieldSpecified;
            }
            set {
                this.current_WeightFieldSpecified = value;
                this.RaisePropertyChanged("Current_WeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Inbound_Document_Type Inbound_Document_Type {
            get {
                return this.inbound_Document_TypeField;
            }
            set {
                this.inbound_Document_TypeField = value;
                this.RaisePropertyChanged("Inbound_Document_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inbound_Document_TypeSpecified {
            get {
                return this.inbound_Document_TypeFieldSpecified;
            }
            set {
                this.inbound_Document_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Inbound_Document_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Inbound_Document_No {
            get {
                return this.inbound_Document_NoField;
            }
            set {
                this.inbound_Document_NoField = value;
                this.RaisePropertyChanged("Inbound_Document_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Inbound_Doc_Line_No {
            get {
                return this.inbound_Doc_Line_NoField;
            }
            set {
                this.inbound_Doc_Line_NoField = value;
                this.RaisePropertyChanged("Inbound_Doc_Line_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inbound_Doc_Line_NoSpecified {
            get {
                return this.inbound_Doc_Line_NoFieldSpecified;
            }
            set {
                this.inbound_Doc_Line_NoFieldSpecified = value;
                this.RaisePropertyChanged("Inbound_Doc_Line_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Outbound_Document_Type Outbound_Document_Type {
            get {
                return this.outbound_Document_TypeField;
            }
            set {
                this.outbound_Document_TypeField = value;
                this.RaisePropertyChanged("Outbound_Document_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outbound_Document_TypeSpecified {
            get {
                return this.outbound_Document_TypeFieldSpecified;
            }
            set {
                this.outbound_Document_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Outbound_Document_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Outbound_Document_No {
            get {
                return this.outbound_Document_NoField;
            }
            set {
                this.outbound_Document_NoField = value;
                this.RaisePropertyChanged("Outbound_Document_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Outbound_Doc_Line_No {
            get {
                return this.outbound_Doc_Line_NoField;
            }
            set {
                this.outbound_Doc_Line_NoField = value;
                this.RaisePropertyChanged("Outbound_Doc_Line_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outbound_Doc_Line_NoSpecified {
            get {
                return this.outbound_Doc_Line_NoFieldSpecified;
            }
            set {
                this.outbound_Doc_Line_NoFieldSpecified = value;
                this.RaisePropertyChanged("Outbound_Doc_Line_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Last_Entry_No {
            get {
                return this.last_Entry_NoField;
            }
            set {
                this.last_Entry_NoField = value;
                this.RaisePropertyChanged("Last_Entry_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Entry_NoSpecified {
            get {
                return this.last_Entry_NoFieldSpecified;
            }
            set {
                this.last_Entry_NoFieldSpecified = value;
                this.RaisePropertyChanged("Last_Entry_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Pallet_Journal_Line_Exist {
            get {
                return this.pallet_Journal_Line_ExistField;
            }
            set {
                this.pallet_Journal_Line_ExistField = value;
                this.RaisePropertyChanged("Pallet_Journal_Line_Exist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pallet_Journal_Line_ExistSpecified {
            get {
                return this.pallet_Journal_Line_ExistFieldSpecified;
            }
            set {
                this.pallet_Journal_Line_ExistFieldSpecified = value;
                this.RaisePropertyChanged("Pallet_Journal_Line_ExistSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal Qty_on_pallet_Jnl {
            get {
                return this.qty_on_pallet_JnlField;
            }
            set {
                this.qty_on_pallet_JnlField = value;
                this.RaisePropertyChanged("Qty_on_pallet_Jnl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_on_pallet_JnlSpecified {
            get {
                return this.qty_on_pallet_JnlFieldSpecified;
            }
            set {
                this.qty_on_pallet_JnlFieldSpecified = value;
                this.RaisePropertyChanged("Qty_on_pallet_JnlSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=14)]
        public System.DateTime Creation_Date {
            get {
                return this.creation_DateField;
            }
            set {
                this.creation_DateField = value;
                this.RaisePropertyChanged("Creation_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_DateSpecified {
            get {
                return this.creation_DateFieldSpecified;
            }
            set {
                this.creation_DateFieldSpecified = value;
                this.RaisePropertyChanged("Creation_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=15)]
        public System.DateTime Creation_Time {
            get {
                return this.creation_TimeField;
            }
            set {
                this.creation_TimeField = value;
                this.RaisePropertyChanged("Creation_Time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Creation_TimeSpecified {
            get {
                return this.creation_TimeFieldSpecified;
            }
            set {
                this.creation_TimeFieldSpecified = value;
                this.RaisePropertyChanged("Creation_TimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string No_Series {
            get {
                return this.no_SeriesField;
            }
            set {
                this.no_SeriesField = value;
                this.RaisePropertyChanged("No_Series");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Bin_code {
            get {
                return this.bin_codeField;
            }
            set {
                this.bin_codeField = value;
                this.RaisePropertyChanged("Bin_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Item_No {
            get {
                return this.item_NoField;
            }
            set {
                this.item_NoField = value;
                this.RaisePropertyChanged("Item_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Lot_No {
            get {
                return this.lot_NoField;
            }
            set {
                this.lot_NoField = value;
                this.RaisePropertyChanged("Lot_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=20)]
        public System.DateTime DLC {
            get {
                return this.dLCField;
            }
            set {
                this.dLCField = value;
                this.RaisePropertyChanged("DLC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DLCSpecified {
            get {
                return this.dLCFieldSpecified;
            }
            set {
                this.dLCFieldSpecified = value;
                this.RaisePropertyChanged("DLCSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int Display_order {
            get {
                return this.display_orderField;
            }
            set {
                this.display_orderField = value;
                this.RaisePropertyChanged("Display_order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Display_orderSpecified {
            get {
                return this.display_orderFieldSpecified;
            }
            set {
                this.display_orderFieldSpecified = value;
                this.RaisePropertyChanged("Display_orderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Item_Description {
            get {
                return this.item_DescriptionField;
            }
            set {
                this.item_DescriptionField = value;
                this.RaisePropertyChanged("Item_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int Nbre_bacs_reception {
            get {
                return this.nbre_bacs_receptionField;
            }
            set {
                this.nbre_bacs_receptionField = value;
                this.RaisePropertyChanged("Nbre_bacs_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Nbre_bacs_receptionSpecified {
            get {
                return this.nbre_bacs_receptionFieldSpecified;
            }
            set {
                this.nbre_bacs_receptionFieldSpecified = value;
                this.RaisePropertyChanged("Nbre_bacs_receptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Type_bacs_reception {
            get {
                return this.type_bacs_receptionField;
            }
            set {
                this.type_bacs_receptionField = value;
                this.RaisePropertyChanged("Type_bacs_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Type_palette_reception {
            get {
                return this.type_palette_receptionField;
            }
            set {
                this.type_palette_receptionField = value;
                this.RaisePropertyChanged("Type_palette_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int Temperature_reception {
            get {
                return this.temperature_receptionField;
            }
            set {
                this.temperature_receptionField = value;
                this.RaisePropertyChanged("Temperature_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Temperature_receptionSpecified {
            get {
                return this.temperature_receptionFieldSpecified;
            }
            set {
                this.temperature_receptionFieldSpecified = value;
                this.RaisePropertyChanged("Temperature_receptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Poids_brut_reception {
            get {
                return this.poids_brut_receptionField;
            }
            set {
                this.poids_brut_receptionField = value;
                this.RaisePropertyChanged("Poids_brut_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Poids_brut_receptionSpecified {
            get {
                return this.poids_brut_receptionFieldSpecified;
            }
            set {
                this.poids_brut_receptionFieldSpecified = value;
                this.RaisePropertyChanged("Poids_brut_receptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Quai_reception {
            get {
                return this.quai_receptionField;
            }
            set {
                this.quai_receptionField = value;
                this.RaisePropertyChanged("Quai_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string User_reception {
            get {
                return this.user_receptionField;
            }
            set {
                this.user_receptionField = value;
                this.RaisePropertyChanged("User_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool Lot_bloque {
            get {
                return this.lot_bloqueField;
            }
            set {
                this.lot_bloqueField = value;
                this.RaisePropertyChanged("Lot_bloque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Lot_bloqueSpecified {
            get {
                return this.lot_bloqueFieldSpecified;
            }
            set {
                this.lot_bloqueFieldSpecified = value;
                this.RaisePropertyChanged("Lot_bloqueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal Quantite_reception {
            get {
                return this.quantite_receptionField;
            }
            set {
                this.quantite_receptionField = value;
                this.RaisePropertyChanged("Quantite_reception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantite_receptionSpecified {
            get {
                return this.quantite_receptionFieldSpecified;
            }
            set {
                this.quantite_receptionFieldSpecified = value;
                this.RaisePropertyChanged("Quantite_receptionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets")]
    public enum Inbound_Document_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Production_Order,
        
        /// <remarks/>
        Positive_Adjustement,
        
        /// <remarks/>
        Purchase_Order,
        
        /// <remarks/>
        Sales_Return,
        
        /// <remarks/>
        Transfer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets")]
    public enum Outbound_Document_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Consumption,
        
        /// <remarks/>
        Negative_Adjustement,
        
        /// <remarks/>
        Sales_Shipment,
        
        /// <remarks/>
        Shipping_Document,
        
        /// <remarks/>
        Consignation_Document,
        
        /// <remarks/>
        Deconsignation_Document,
        
        /// <remarks/>
        Transfer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets")]
    public partial class Pallets_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Pallets_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Pallets_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets")]
    public enum Pallets_Fields {
        
        /// <remarks/>
        SSCC_No,
        
        /// <remarks/>
        Location_code,
        
        /// <remarks/>
        Current_Quantity,
        
        /// <remarks/>
        Current_Weight,
        
        /// <remarks/>
        Inbound_Document_Type,
        
        /// <remarks/>
        Inbound_Document_No,
        
        /// <remarks/>
        Inbound_Doc_Line_No,
        
        /// <remarks/>
        Outbound_Document_Type,
        
        /// <remarks/>
        Outbound_Document_No,
        
        /// <remarks/>
        Outbound_Doc_Line_No,
        
        /// <remarks/>
        Last_Entry_No,
        
        /// <remarks/>
        Pallet_Journal_Line_Exist,
        
        /// <remarks/>
        Qty_on_pallet_Jnl,
        
        /// <remarks/>
        Creation_Date,
        
        /// <remarks/>
        Creation_Time,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Bin_code,
        
        /// <remarks/>
        Item_No,
        
        /// <remarks/>
        Lot_No,
        
        /// <remarks/>
        DLC,
        
        /// <remarks/>
        Display_order,
        
        /// <remarks/>
        Item_Description,
        
        /// <remarks/>
        Nbre_bacs_reception,
        
        /// <remarks/>
        Type_bacs_reception,
        
        /// <remarks/>
        Type_palette_reception,
        
        /// <remarks/>
        Temperature_reception,
        
        /// <remarks/>
        Poids_brut_reception,
        
        /// <remarks/>
        Quai_reception,
        
        /// <remarks/>
        User_reception,
        
        /// <remarks/>
        Lot_bloque,
        
        /// <remarks/>
        Quantite_reception,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string SSCC_No;
        
        public Read() {
        }
        
        public Read(string SSCC_No) {
            this.SSCC_No = SSCC_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public Read_Result() {
        }
        
        public Read_Result(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ScanCongel.ServiceReference1.Pallets_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ScanCongel.ServiceReference1.Pallets_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ServiceReference1.Pallets[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ScanCongel.ServiceReference1.Pallets[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public Create() {
        }
        
        public Create(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public Create_Result() {
        }
        
        public Create_Result(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ServiceReference1.Pallets[] Pallets_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            this.Pallets_List = Pallets_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ServiceReference1.Pallets[] Pallets_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            this.Pallets_List = Pallets_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public Update() {
        }
        
        public Update(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public ScanCongel.ServiceReference1.Pallets Pallets;
        
        public Update_Result() {
        }
        
        public Update_Result(ScanCongel.ServiceReference1.Pallets Pallets) {
            this.Pallets = Pallets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ServiceReference1.Pallets[] Pallets_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            this.Pallets_List = Pallets_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ServiceReference1.Pallets[] Pallets_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            this.Pallets_List = Pallets_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pallets", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/pallets", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Pallets_PortChannel : ScanCongel.ServiceReference1.Pallets_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Pallets_PortClient : System.ServiceModel.ClientBase<ScanCongel.ServiceReference1.Pallets_Port>, ScanCongel.ServiceReference1.Pallets_Port {
        
        public Pallets_PortClient() {
        }
        
        public Pallets_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Pallets_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pallets_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Pallets_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.Read_Result ScanCongel.ServiceReference1.Pallets_Port.Read(ScanCongel.ServiceReference1.Read request) {
            return base.Channel.Read(request);
        }
        
        public ScanCongel.ServiceReference1.Pallets Read(string SSCC_No) {
            ScanCongel.ServiceReference1.Read inValue = new ScanCongel.ServiceReference1.Read();
            inValue.SSCC_No = SSCC_No;
            ScanCongel.ServiceReference1.Read_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).Read(inValue);
            return retVal.Pallets;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Read_Result> ScanCongel.ServiceReference1.Pallets_Port.ReadAsync(ScanCongel.ServiceReference1.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Read_Result> ReadAsync(string SSCC_No) {
            ScanCongel.ServiceReference1.Read inValue = new ScanCongel.ServiceReference1.Read();
            inValue.SSCC_No = SSCC_No;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.ReadByRecId_Result ScanCongel.ServiceReference1.Pallets_Port.ReadByRecId(ScanCongel.ServiceReference1.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ScanCongel.ServiceReference1.Pallets ReadByRecId(string recId) {
            ScanCongel.ServiceReference1.ReadByRecId inValue = new ScanCongel.ServiceReference1.ReadByRecId();
            inValue.recId = recId;
            ScanCongel.ServiceReference1.ReadByRecId_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).ReadByRecId(inValue);
            return retVal.Pallets;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadByRecId_Result> ScanCongel.ServiceReference1.Pallets_Port.ReadByRecIdAsync(ScanCongel.ServiceReference1.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ScanCongel.ServiceReference1.ReadByRecId inValue = new ScanCongel.ServiceReference1.ReadByRecId();
            inValue.recId = recId;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.ReadMultiple_Result ScanCongel.ServiceReference1.Pallets_Port.ReadMultiple(ScanCongel.ServiceReference1.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ScanCongel.ServiceReference1.Pallets[] ReadMultiple(ScanCongel.ServiceReference1.Pallets_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.ServiceReference1.ReadMultiple inValue = new ScanCongel.ServiceReference1.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ScanCongel.ServiceReference1.ReadMultiple_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadMultiple_Result> ScanCongel.ServiceReference1.Pallets_Port.ReadMultipleAsync(ScanCongel.ServiceReference1.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.ServiceReference1.Pallets_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.ServiceReference1.ReadMultiple inValue = new ScanCongel.ServiceReference1.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.IsUpdated_Result ScanCongel.ServiceReference1.Pallets_Port.IsUpdated(ScanCongel.ServiceReference1.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ScanCongel.ServiceReference1.IsUpdated inValue = new ScanCongel.ServiceReference1.IsUpdated();
            inValue.Key = Key;
            ScanCongel.ServiceReference1.IsUpdated_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.IsUpdated_Result> ScanCongel.ServiceReference1.Pallets_Port.IsUpdatedAsync(ScanCongel.ServiceReference1.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ScanCongel.ServiceReference1.IsUpdated inValue = new ScanCongel.ServiceReference1.IsUpdated();
            inValue.Key = Key;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.GetRecIdFromKey_Result ScanCongel.ServiceReference1.Pallets_Port.GetRecIdFromKey(ScanCongel.ServiceReference1.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ScanCongel.ServiceReference1.GetRecIdFromKey inValue = new ScanCongel.ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            ScanCongel.ServiceReference1.GetRecIdFromKey_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.GetRecIdFromKey_Result> ScanCongel.ServiceReference1.Pallets_Port.GetRecIdFromKeyAsync(ScanCongel.ServiceReference1.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ScanCongel.ServiceReference1.GetRecIdFromKey inValue = new ScanCongel.ServiceReference1.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.Create_Result ScanCongel.ServiceReference1.Pallets_Port.Create(ScanCongel.ServiceReference1.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ScanCongel.ServiceReference1.Pallets Pallets) {
            ScanCongel.ServiceReference1.Create inValue = new ScanCongel.ServiceReference1.Create();
            inValue.Pallets = Pallets;
            ScanCongel.ServiceReference1.Create_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).Create(inValue);
            Pallets = retVal.Pallets;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Create_Result> CreateAsync(ScanCongel.ServiceReference1.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.CreateMultiple_Result ScanCongel.ServiceReference1.Pallets_Port.CreateMultiple(ScanCongel.ServiceReference1.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            ScanCongel.ServiceReference1.CreateMultiple inValue = new ScanCongel.ServiceReference1.CreateMultiple();
            inValue.Pallets_List = Pallets_List;
            ScanCongel.ServiceReference1.CreateMultiple_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).CreateMultiple(inValue);
            Pallets_List = retVal.Pallets_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.ServiceReference1.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.Update_Result ScanCongel.ServiceReference1.Pallets_Port.Update(ScanCongel.ServiceReference1.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ScanCongel.ServiceReference1.Pallets Pallets) {
            ScanCongel.ServiceReference1.Update inValue = new ScanCongel.ServiceReference1.Update();
            inValue.Pallets = Pallets;
            ScanCongel.ServiceReference1.Update_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).Update(inValue);
            Pallets = retVal.Pallets;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Update_Result> UpdateAsync(ScanCongel.ServiceReference1.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.UpdateMultiple_Result ScanCongel.ServiceReference1.Pallets_Port.UpdateMultiple(ScanCongel.ServiceReference1.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ScanCongel.ServiceReference1.Pallets[] Pallets_List) {
            ScanCongel.ServiceReference1.UpdateMultiple inValue = new ScanCongel.ServiceReference1.UpdateMultiple();
            inValue.Pallets_List = Pallets_List;
            ScanCongel.ServiceReference1.UpdateMultiple_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).UpdateMultiple(inValue);
            Pallets_List = retVal.Pallets_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.ServiceReference1.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ServiceReference1.Delete_Result ScanCongel.ServiceReference1.Pallets_Port.Delete(ScanCongel.ServiceReference1.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ScanCongel.ServiceReference1.Delete inValue = new ScanCongel.ServiceReference1.Delete();
            inValue.Key = Key;
            ScanCongel.ServiceReference1.Delete_Result retVal = ((ScanCongel.ServiceReference1.Pallets_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Delete_Result> ScanCongel.ServiceReference1.Pallets_Port.DeleteAsync(ScanCongel.ServiceReference1.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ServiceReference1.Delete_Result> DeleteAsync(string Key) {
            ScanCongel.ServiceReference1.Delete inValue = new ScanCongel.ServiceReference1.Delete();
            inValue.Key = Key;
            return ((ScanCongel.ServiceReference1.Pallets_Port)(this)).DeleteAsync(inValue);
        }
    }
}
