//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCongel.ReservationsPalettes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", ConfigurationName="ReservationsPalettes.ReservationsPalettes_Port")]
    public interface ReservationsPalettes_Port {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Read_Result) du message Read_Result ne correspond pas à la valeur par défaut (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.Read_Result Read(ScanCongel.ReservationsPalettes.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Read_Result> ReadAsync(ScanCongel.ReservationsPalettes.Read request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadByRecId_Result) du message ReadByRecId_Result ne correspond pas à la valeur par défaut (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.ReadByRecId_Result ReadByRecId(ScanCongel.ReservationsPalettes.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadByRecId_Result> ReadByRecIdAsync(ScanCongel.ReservationsPalettes.ReadByRecId request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadMultiple_Result) du message ReadMultiple_Result ne correspond pas à la valeur par défaut (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.ReadMultiple_Result ReadMultiple(ScanCongel.ReservationsPalettes.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.ReservationsPalettes.ReadMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (IsUpdated_Result) du message IsUpdated_Result ne correspond pas à la valeur par défaut (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.IsUpdated_Result IsUpdated(ScanCongel.ReservationsPalettes.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.IsUpdated_Result> IsUpdatedAsync(ScanCongel.ReservationsPalettes.IsUpdated request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (GetRecIdFromKey_Result) du message GetRecIdFromKey_Result ne correspond pas à la valeur par défaut (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result GetRecIdFromKey(ScanCongel.ReservationsPalettes.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ScanCongel.ReservationsPalettes.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.Create_Result Create(ScanCongel.ReservationsPalettes.Create request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Create_Result> CreateAsync(ScanCongel.ReservationsPalettes.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.CreateMultiple_Result CreateMultiple(ScanCongel.ReservationsPalettes.CreateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.ReservationsPalettes.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.Update_Result Update(ScanCongel.ReservationsPalettes.Update request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Update_Result> UpdateAsync(ScanCongel.ReservationsPalettes.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.UpdateMultiple_Result UpdateMultiple(ScanCongel.ReservationsPalettes.UpdateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.ReservationsPalettes.UpdateMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Delete_Result) du message Delete_Result ne correspond pas à la valeur par défaut (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.ReservationsPalettes.Delete_Result Delete(ScanCongel.ReservationsPalettes.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/reservationspalettes:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Delete_Result> DeleteAsync(ScanCongel.ReservationsPalettes.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes")]
    public partial class ReservationsPalettes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int reservation_entryField;
        
        private bool reservation_entryFieldSpecified;
        
        private string sSCC_NoField;
        
        private decimal current_QuantityField;
        
        private bool current_QuantityFieldSpecified;
        
        private string lot_NoField;
        
        private string bin_CodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Reservation_entry {
            get {
                return this.reservation_entryField;
            }
            set {
                this.reservation_entryField = value;
                this.RaisePropertyChanged("Reservation_entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reservation_entrySpecified {
            get {
                return this.reservation_entryFieldSpecified;
            }
            set {
                this.reservation_entryFieldSpecified = value;
                this.RaisePropertyChanged("Reservation_entrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SSCC_No {
            get {
                return this.sSCC_NoField;
            }
            set {
                this.sSCC_NoField = value;
                this.RaisePropertyChanged("SSCC_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Current_Quantity {
            get {
                return this.current_QuantityField;
            }
            set {
                this.current_QuantityField = value;
                this.RaisePropertyChanged("Current_Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Current_QuantitySpecified {
            get {
                return this.current_QuantityFieldSpecified;
            }
            set {
                this.current_QuantityFieldSpecified = value;
                this.RaisePropertyChanged("Current_QuantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Lot_No {
            get {
                return this.lot_NoField;
            }
            set {
                this.lot_NoField = value;
                this.RaisePropertyChanged("Lot_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Bin_Code {
            get {
                return this.bin_CodeField;
            }
            set {
                this.bin_CodeField = value;
                this.RaisePropertyChanged("Bin_Code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes")]
    public partial class ReservationsPalettes_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReservationsPalettes_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReservationsPalettes_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes")]
    public enum ReservationsPalettes_Fields {
        
        /// <remarks/>
        Reservation_entry,
        
        /// <remarks/>
        SSCC_No,
        
        /// <remarks/>
        Current_Quantity,
        
        /// <remarks/>
        Lot_No,
        
        /// <remarks/>
        Bin_Code,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public int Reservation_entry;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=1)]
        public string SSCC_No;
        
        public Read() {
        }
        
        public Read(int Reservation_entry, string SSCC_No) {
            this.Reservation_entry = Reservation_entry;
            this.SSCC_No = SSCC_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public Read_Result() {
        }
        
        public Read_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ScanCongel.ReservationsPalettes.ReservationsPalettes_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public Create() {
        }
        
        public Create(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public Create_Result() {
        }
        
        public Create_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            this.ReservationsPalettes_List = ReservationsPalettes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            this.ReservationsPalettes_List = ReservationsPalettes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public Update() {
        }
        
        public Update(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes;
        
        public Update_Result() {
        }
        
        public Update_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            this.ReservationsPalettes = ReservationsPalettes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            this.ReservationsPalettes_List = ReservationsPalettes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            this.ReservationsPalettes_List = ReservationsPalettes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/reservationspalettes", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationsPalettes_PortChannel : ScanCongel.ReservationsPalettes.ReservationsPalettes_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationsPalettes_PortClient : System.ServiceModel.ClientBase<ScanCongel.ReservationsPalettes.ReservationsPalettes_Port>, ScanCongel.ReservationsPalettes.ReservationsPalettes_Port {
        
        public ReservationsPalettes_PortClient() {
        }
        
        public ReservationsPalettes_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationsPalettes_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsPalettes_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationsPalettes_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.Read_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.Read(ScanCongel.ReservationsPalettes.Read request) {
            return base.Channel.Read(request);
        }
        
        public ScanCongel.ReservationsPalettes.ReservationsPalettes Read(int Reservation_entry, string SSCC_No) {
            ScanCongel.ReservationsPalettes.Read inValue = new ScanCongel.ReservationsPalettes.Read();
            inValue.Reservation_entry = Reservation_entry;
            inValue.SSCC_No = SSCC_No;
            ScanCongel.ReservationsPalettes.Read_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).Read(inValue);
            return retVal.ReservationsPalettes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Read_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.ReadAsync(ScanCongel.ReservationsPalettes.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Read_Result> ReadAsync(int Reservation_entry, string SSCC_No) {
            ScanCongel.ReservationsPalettes.Read inValue = new ScanCongel.ReservationsPalettes.Read();
            inValue.Reservation_entry = Reservation_entry;
            inValue.SSCC_No = SSCC_No;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.ReadByRecId_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.ReadByRecId(ScanCongel.ReservationsPalettes.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ScanCongel.ReservationsPalettes.ReservationsPalettes ReadByRecId(string recId) {
            ScanCongel.ReservationsPalettes.ReadByRecId inValue = new ScanCongel.ReservationsPalettes.ReadByRecId();
            inValue.recId = recId;
            ScanCongel.ReservationsPalettes.ReadByRecId_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).ReadByRecId(inValue);
            return retVal.ReservationsPalettes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadByRecId_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.ReadByRecIdAsync(ScanCongel.ReservationsPalettes.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ScanCongel.ReservationsPalettes.ReadByRecId inValue = new ScanCongel.ReservationsPalettes.ReadByRecId();
            inValue.recId = recId;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.ReadMultiple_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.ReadMultiple(ScanCongel.ReservationsPalettes.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReadMultiple(ScanCongel.ReservationsPalettes.ReservationsPalettes_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.ReservationsPalettes.ReadMultiple inValue = new ScanCongel.ReservationsPalettes.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ScanCongel.ReservationsPalettes.ReadMultiple_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadMultiple_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.ReadMultipleAsync(ScanCongel.ReservationsPalettes.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.ReservationsPalettes.ReservationsPalettes_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.ReservationsPalettes.ReadMultiple inValue = new ScanCongel.ReservationsPalettes.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.IsUpdated_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.IsUpdated(ScanCongel.ReservationsPalettes.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ScanCongel.ReservationsPalettes.IsUpdated inValue = new ScanCongel.ReservationsPalettes.IsUpdated();
            inValue.Key = Key;
            ScanCongel.ReservationsPalettes.IsUpdated_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.IsUpdated_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.IsUpdatedAsync(ScanCongel.ReservationsPalettes.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ScanCongel.ReservationsPalettes.IsUpdated inValue = new ScanCongel.ReservationsPalettes.IsUpdated();
            inValue.Key = Key;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.GetRecIdFromKey(ScanCongel.ReservationsPalettes.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ScanCongel.ReservationsPalettes.GetRecIdFromKey inValue = new ScanCongel.ReservationsPalettes.GetRecIdFromKey();
            inValue.Key = Key;
            ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.GetRecIdFromKeyAsync(ScanCongel.ReservationsPalettes.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ScanCongel.ReservationsPalettes.GetRecIdFromKey inValue = new ScanCongel.ReservationsPalettes.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.Create_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.Create(ScanCongel.ReservationsPalettes.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            ScanCongel.ReservationsPalettes.Create inValue = new ScanCongel.ReservationsPalettes.Create();
            inValue.ReservationsPalettes = ReservationsPalettes;
            ScanCongel.ReservationsPalettes.Create_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).Create(inValue);
            ReservationsPalettes = retVal.ReservationsPalettes;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Create_Result> CreateAsync(ScanCongel.ReservationsPalettes.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.CreateMultiple_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.CreateMultiple(ScanCongel.ReservationsPalettes.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            ScanCongel.ReservationsPalettes.CreateMultiple inValue = new ScanCongel.ReservationsPalettes.CreateMultiple();
            inValue.ReservationsPalettes_List = ReservationsPalettes_List;
            ScanCongel.ReservationsPalettes.CreateMultiple_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).CreateMultiple(inValue);
            ReservationsPalettes_List = retVal.ReservationsPalettes_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.ReservationsPalettes.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.Update_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.Update(ScanCongel.ReservationsPalettes.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ScanCongel.ReservationsPalettes.ReservationsPalettes ReservationsPalettes) {
            ScanCongel.ReservationsPalettes.Update inValue = new ScanCongel.ReservationsPalettes.Update();
            inValue.ReservationsPalettes = ReservationsPalettes;
            ScanCongel.ReservationsPalettes.Update_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).Update(inValue);
            ReservationsPalettes = retVal.ReservationsPalettes;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Update_Result> UpdateAsync(ScanCongel.ReservationsPalettes.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.UpdateMultiple_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.UpdateMultiple(ScanCongel.ReservationsPalettes.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ScanCongel.ReservationsPalettes.ReservationsPalettes[] ReservationsPalettes_List) {
            ScanCongel.ReservationsPalettes.UpdateMultiple inValue = new ScanCongel.ReservationsPalettes.UpdateMultiple();
            inValue.ReservationsPalettes_List = ReservationsPalettes_List;
            ScanCongel.ReservationsPalettes.UpdateMultiple_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).UpdateMultiple(inValue);
            ReservationsPalettes_List = retVal.ReservationsPalettes_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.ReservationsPalettes.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ReservationsPalettes.Delete_Result ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.Delete(ScanCongel.ReservationsPalettes.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ScanCongel.ReservationsPalettes.Delete inValue = new ScanCongel.ReservationsPalettes.Delete();
            inValue.Key = Key;
            ScanCongel.ReservationsPalettes.Delete_Result retVal = ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Delete_Result> ScanCongel.ReservationsPalettes.ReservationsPalettes_Port.DeleteAsync(ScanCongel.ReservationsPalettes.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ReservationsPalettes.Delete_Result> DeleteAsync(string Key) {
            ScanCongel.ReservationsPalettes.Delete inValue = new ScanCongel.ReservationsPalettes.Delete();
            inValue.Key = Key;
            return ((ScanCongel.ReservationsPalettes.ReservationsPalettes_Port)(this)).DeleteAsync(inValue);
        }
    }
}
