//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCongel.ScanCU {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", ConfigurationName="ScanCU.Scan_Port")]
    public interface Scan_Port {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PutAwayPallet_Result) du message PutAwayPallet_Result ne correspond pas à la valeur par défaut (PutAwayPallet)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PutAwayPallet", ReplyAction="*")]
        ScanCongel.ScanCU.PutAwayPallet_Result PutAwayPallet(ScanCongel.ScanCU.PutAwayPallet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PutAwayPallet", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPallet_Result> PutAwayPalletAsync(ScanCongel.ScanCU.PutAwayPallet request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PutAwayPalletWithUser_Result) du message PutAwayPalletWithUser_Result ne correspond pas à la valeur par défaut (PutAwayPalletWithUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PutAwayPalletWithUser", ReplyAction="*")]
        ScanCongel.ScanCU.PutAwayPalletWithUser_Result PutAwayPalletWithUser(ScanCongel.ScanCU.PutAwayPalletWithUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PutAwayPalletWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPalletWithUser_Result> PutAwayPalletWithUserAsync(ScanCongel.ScanCU.PutAwayPalletWithUser request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (AddPickingPallet_Result) du message AddPickingPallet_Result ne correspond pas à la valeur par défaut (AddPickingPallet)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:AddPickingPallet", ReplyAction="*")]
        ScanCongel.ScanCU.AddPickingPallet_Result AddPickingPallet(ScanCongel.ScanCU.AddPickingPallet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:AddPickingPallet", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPallet_Result> AddPickingPalletAsync(ScanCongel.ScanCU.AddPickingPallet request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (AddPickingPalletWithUser_Result) du message AddPickingPalletWithUser_Result ne correspond pas à la valeur par défaut (AddPickingPalletWithUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:AddPickingPalletWithUser", ReplyAction="*")]
        ScanCongel.ScanCU.AddPickingPalletWithUser_Result AddPickingPalletWithUser(ScanCongel.ScanCU.AddPickingPalletWithUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:AddPickingPalletWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPalletWithUser_Result> AddPickingPalletWithUserAsync(ScanCongel.ScanCU.AddPickingPalletWithUser request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ValidatePicking_Result) du message ValidatePicking_Result ne correspond pas à la valeur par défaut (ValidatePicking)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePicking", ReplyAction="*")]
        ScanCongel.ScanCU.ValidatePicking_Result ValidatePicking(ScanCongel.ScanCU.ValidatePicking request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePicking", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePicking_Result> ValidatePickingAsync(ScanCongel.ScanCU.ValidatePicking request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ValidatePickingWithUser_Result) du message ValidatePickingWithUser_Result ne correspond pas à la valeur par défaut (ValidatePickingWithUser)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePickingWithUser", ReplyAction="*")]
        ScanCongel.ScanCU.ValidatePickingWithUser_Result ValidatePickingWithUser(ScanCongel.ScanCU.ValidatePickingWithUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePickingWithUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePickingWithUser_Result> ValidatePickingWithUserAsync(ScanCongel.ScanCU.ValidatePickingWithUser request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ValidatePurchOrder_Result) du message ValidatePurchOrder_Result ne correspond pas à la valeur par défaut (ValidatePurchOrder)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePurchOrder", ReplyAction="*")]
        ScanCongel.ScanCU.ValidatePurchOrder_Result ValidatePurchOrder(ScanCongel.ScanCU.ValidatePurchOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePurchOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePurchOrder_Result> ValidatePurchOrderAsync(ScanCongel.ScanCU.ValidatePurchOrder request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (MakeOTSFromPurchOrder_Result) du message MakeOTSFromPurchOrder_Result ne correspond pas à la valeur par défaut (MakeOTSFromPurchOrder)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:MakeOTSFromPurchOrder", ReplyAction="*")]
        ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result MakeOTSFromPurchOrder(ScanCongel.ScanCU.MakeOTSFromPurchOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:MakeOTSFromPurchOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result> MakeOTSFromPurchOrderAsync(ScanCongel.ScanCU.MakeOTSFromPurchOrder request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PrintLabel_Result) du message PrintLabel_Result ne correspond pas à la valeur par défaut (PrintLabel)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintLabel", ReplyAction="*")]
        ScanCongel.ScanCU.PrintLabel_Result PrintLabel(ScanCongel.ScanCU.PrintLabel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintLabel", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintLabel_Result> PrintLabelAsync(ScanCongel.ScanCU.PrintLabel request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PrintReceipt_Result) du message PrintReceipt_Result ne correspond pas à la valeur par défaut (PrintReceipt)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintReceipt", ReplyAction="*")]
        ScanCongel.ScanCU.PrintReceipt_Result PrintReceipt(ScanCongel.ScanCU.PrintReceipt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintReceipt_Result> PrintReceiptAsync(ScanCongel.ScanCU.PrintReceipt request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PrintFichePaletteProduction_Result) du message PrintFichePaletteProduction_Result ne correspond pas à la valeur par défaut (PrintFichePaletteProduction)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintFichePaletteProduction", ReplyAction="*")]
        ScanCongel.ScanCU.PrintFichePaletteProduction_Result PrintFichePaletteProduction(ScanCongel.ScanCU.PrintFichePaletteProduction request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PrintFichePaletteProduction", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintFichePaletteProduction_Result> PrintFichePaletteProductionAsync(ScanCongel.ScanCU.PrintFichePaletteProduction request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ValidatePaletteProduction_Result) du message ValidatePaletteProduction_Result ne correspond pas à la valeur par défaut (ValidatePaletteProduction)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePaletteProduction", ReplyAction="*")]
        ScanCongel.ScanCU.ValidatePaletteProduction_Result ValidatePaletteProduction(ScanCongel.ScanCU.ValidatePaletteProduction request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:ValidatePaletteProduction", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePaletteProduction_Result> ValidatePaletteProductionAsync(ScanCongel.ScanCU.ValidatePaletteProduction request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (TftFromProdToCongel_Result) du message TftFromProdToCongel_Result ne correspond pas à la valeur par défaut (TftFromProdToCongel)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:TftFromProdToCongel", ReplyAction="*")]
        ScanCongel.ScanCU.TftFromProdToCongel_Result TftFromProdToCongel(ScanCongel.ScanCU.TftFromProdToCongel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:TftFromProdToCongel", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.TftFromProdToCongel_Result> TftFromProdToCongelAsync(ScanCongel.ScanCU.TftFromProdToCongel request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (PalletInventory_Result) du message PalletInventory_Result ne correspond pas à la valeur par défaut (PalletInventory)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PalletInventory", ReplyAction="*")]
        ScanCongel.ScanCU.PalletInventory_Result PalletInventory(ScanCongel.ScanCU.PalletInventory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Scan:PalletInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PalletInventory_Result> PalletInventoryAsync(ScanCongel.ScanCU.PalletInventory request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAwayPallet", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PutAwayPallet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCCNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string newBin;
        
        public PutAwayPallet() {
        }
        
        public PutAwayPallet(string sSCCNo, string newBin) {
            this.sSCCNo = sSCCNo;
            this.newBin = newBin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAwayPallet_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PutAwayPallet_Result {
        
        public PutAwayPallet_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAwayPalletWithUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PutAwayPalletWithUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCCNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string newBin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public string user;
        
        public PutAwayPalletWithUser() {
        }
        
        public PutAwayPalletWithUser(string sSCCNo, string newBin, string user) {
            this.sSCCNo = sSCCNo;
            this.newBin = newBin;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutAwayPalletWithUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PutAwayPalletWithUser_Result {
        
        public PutAwayPalletWithUser_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPickingPallet", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class AddPickingPallet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public int lineNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=3)]
        public decimal qty;
        
        public AddPickingPallet() {
        }
        
        public AddPickingPallet(string sSCC, string orderNo, int lineNo, decimal qty) {
            this.sSCC = sSCC;
            this.orderNo = orderNo;
            this.lineNo = lineNo;
            this.qty = qty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPickingPallet_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class AddPickingPallet_Result {
        
        public AddPickingPallet_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPickingPalletWithUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class AddPickingPalletWithUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public int lineNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=3)]
        public decimal qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=4)]
        public string user;
        
        public AddPickingPalletWithUser() {
        }
        
        public AddPickingPalletWithUser(string sSCC, string orderNo, int lineNo, decimal qty, string user) {
            this.sSCC = sSCC;
            this.orderNo = orderNo;
            this.lineNo = lineNo;
            this.qty = qty;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPickingPalletWithUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class AddPickingPalletWithUser_Result {
        
        public AddPickingPalletWithUser_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePicking", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePicking {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string orderNo;
        
        public ValidatePicking() {
        }
        
        public ValidatePicking(string orderNo) {
            this.orderNo = orderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePicking_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePicking_Result {
        
        public ValidatePicking_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePickingWithUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePickingWithUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string orderNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string user;
        
        public ValidatePickingWithUser() {
        }
        
        public ValidatePickingWithUser(string orderNo, string user) {
            this.orderNo = orderNo;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePickingWithUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePickingWithUser_Result {
        
        public ValidatePickingWithUser_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePurchOrder", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePurchOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string cmd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string expectedReceiptDt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public string magasin;
        
        public ValidatePurchOrder() {
        }
        
        public ValidatePurchOrder(string cmd, string expectedReceiptDt, string magasin) {
            this.cmd = cmd;
            this.expectedReceiptDt = expectedReceiptDt;
            this.magasin = magasin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePurchOrder_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePurchOrder_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string return_value;
        
        public ValidatePurchOrder_Result() {
        }
        
        public ValidatePurchOrder_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MakeOTSFromPurchOrder", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class MakeOTSFromPurchOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string cmd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string expectedReceiptDt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public string magasin;
        
        public MakeOTSFromPurchOrder() {
        }
        
        public MakeOTSFromPurchOrder(string cmd, string expectedReceiptDt, string magasin) {
            this.cmd = cmd;
            this.expectedReceiptDt = expectedReceiptDt;
            this.magasin = magasin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MakeOTSFromPurchOrder_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class MakeOTSFromPurchOrder_Result {
        
        public MakeOTSFromPurchOrder_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintLabel", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintLabel {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCCNo;
        
        public PrintLabel() {
        }
        
        public PrintLabel(string sSCCNo) {
            this.sSCCNo = sSCCNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintLabel_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintLabel_Result {
        
        public PrintLabel_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintReceipt", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintReceipt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string receive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public string quai;
        
        public PrintReceipt() {
        }
        
        public PrintReceipt(string receive, string quai) {
            this.receive = receive;
            this.quai = quai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintReceipt_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintReceipt_Result {
        
        public PrintReceipt_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintFichePaletteProduction", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintFichePaletteProduction {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        public PrintFichePaletteProduction() {
        }
        
        public PrintFichePaletteProduction(string sSCC) {
            this.sSCC = sSCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintFichePaletteProduction_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PrintFichePaletteProduction_Result {
        
        public PrintFichePaletteProduction_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePaletteProduction", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePaletteProduction {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        public ValidatePaletteProduction() {
        }
        
        public ValidatePaletteProduction(string sSCC) {
            this.sSCC = sSCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePaletteProduction_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class ValidatePaletteProduction_Result {
        
        public ValidatePaletteProduction_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TftFromProdToCongel", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class TftFromProdToCongel {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        public TftFromProdToCongel() {
        }
        
        public TftFromProdToCongel(string sSCC) {
            this.sSCC = sSCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TftFromProdToCongel_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class TftFromProdToCongel_Result {
        
        public TftFromProdToCongel_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PalletInventory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PalletInventory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=0)]
        public string sSCC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=1)]
        public decimal newQuantity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Scan", Order=2)]
        public string user;
        
        public PalletInventory() {
        }
        
        public PalletInventory(string sSCC, decimal newQuantity, string user) {
            this.sSCC = sSCC;
            this.newQuantity = newQuantity;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PalletInventory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Scan", IsWrapped=true)]
    public partial class PalletInventory_Result {
        
        public PalletInventory_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Scan_PortChannel : ScanCongel.ScanCU.Scan_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Scan_PortClient : System.ServiceModel.ClientBase<ScanCongel.ScanCU.Scan_Port>, ScanCongel.ScanCU.Scan_Port {
        
        public Scan_PortClient() {
        }
        
        public Scan_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Scan_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Scan_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Scan_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PutAwayPallet_Result ScanCongel.ScanCU.Scan_Port.PutAwayPallet(ScanCongel.ScanCU.PutAwayPallet request) {
            return base.Channel.PutAwayPallet(request);
        }
        
        public void PutAwayPallet(string sSCCNo, string newBin) {
            ScanCongel.ScanCU.PutAwayPallet inValue = new ScanCongel.ScanCU.PutAwayPallet();
            inValue.sSCCNo = sSCCNo;
            inValue.newBin = newBin;
            ScanCongel.ScanCU.PutAwayPallet_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PutAwayPallet(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPallet_Result> ScanCongel.ScanCU.Scan_Port.PutAwayPalletAsync(ScanCongel.ScanCU.PutAwayPallet request) {
            return base.Channel.PutAwayPalletAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPallet_Result> PutAwayPalletAsync(string sSCCNo, string newBin) {
            ScanCongel.ScanCU.PutAwayPallet inValue = new ScanCongel.ScanCU.PutAwayPallet();
            inValue.sSCCNo = sSCCNo;
            inValue.newBin = newBin;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PutAwayPalletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PutAwayPalletWithUser_Result ScanCongel.ScanCU.Scan_Port.PutAwayPalletWithUser(ScanCongel.ScanCU.PutAwayPalletWithUser request) {
            return base.Channel.PutAwayPalletWithUser(request);
        }
        
        public void PutAwayPalletWithUser(string sSCCNo, string newBin, string user) {
            ScanCongel.ScanCU.PutAwayPalletWithUser inValue = new ScanCongel.ScanCU.PutAwayPalletWithUser();
            inValue.sSCCNo = sSCCNo;
            inValue.newBin = newBin;
            inValue.user = user;
            ScanCongel.ScanCU.PutAwayPalletWithUser_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PutAwayPalletWithUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPalletWithUser_Result> ScanCongel.ScanCU.Scan_Port.PutAwayPalletWithUserAsync(ScanCongel.ScanCU.PutAwayPalletWithUser request) {
            return base.Channel.PutAwayPalletWithUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PutAwayPalletWithUser_Result> PutAwayPalletWithUserAsync(string sSCCNo, string newBin, string user) {
            ScanCongel.ScanCU.PutAwayPalletWithUser inValue = new ScanCongel.ScanCU.PutAwayPalletWithUser();
            inValue.sSCCNo = sSCCNo;
            inValue.newBin = newBin;
            inValue.user = user;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PutAwayPalletWithUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.AddPickingPallet_Result ScanCongel.ScanCU.Scan_Port.AddPickingPallet(ScanCongel.ScanCU.AddPickingPallet request) {
            return base.Channel.AddPickingPallet(request);
        }
        
        public void AddPickingPallet(string sSCC, string orderNo, int lineNo, decimal qty) {
            ScanCongel.ScanCU.AddPickingPallet inValue = new ScanCongel.ScanCU.AddPickingPallet();
            inValue.sSCC = sSCC;
            inValue.orderNo = orderNo;
            inValue.lineNo = lineNo;
            inValue.qty = qty;
            ScanCongel.ScanCU.AddPickingPallet_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).AddPickingPallet(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPallet_Result> ScanCongel.ScanCU.Scan_Port.AddPickingPalletAsync(ScanCongel.ScanCU.AddPickingPallet request) {
            return base.Channel.AddPickingPalletAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPallet_Result> AddPickingPalletAsync(string sSCC, string orderNo, int lineNo, decimal qty) {
            ScanCongel.ScanCU.AddPickingPallet inValue = new ScanCongel.ScanCU.AddPickingPallet();
            inValue.sSCC = sSCC;
            inValue.orderNo = orderNo;
            inValue.lineNo = lineNo;
            inValue.qty = qty;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).AddPickingPalletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.AddPickingPalletWithUser_Result ScanCongel.ScanCU.Scan_Port.AddPickingPalletWithUser(ScanCongel.ScanCU.AddPickingPalletWithUser request) {
            return base.Channel.AddPickingPalletWithUser(request);
        }
        
        public void AddPickingPalletWithUser(string sSCC, string orderNo, int lineNo, decimal qty, string user) {
            ScanCongel.ScanCU.AddPickingPalletWithUser inValue = new ScanCongel.ScanCU.AddPickingPalletWithUser();
            inValue.sSCC = sSCC;
            inValue.orderNo = orderNo;
            inValue.lineNo = lineNo;
            inValue.qty = qty;
            inValue.user = user;
            ScanCongel.ScanCU.AddPickingPalletWithUser_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).AddPickingPalletWithUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPalletWithUser_Result> ScanCongel.ScanCU.Scan_Port.AddPickingPalletWithUserAsync(ScanCongel.ScanCU.AddPickingPalletWithUser request) {
            return base.Channel.AddPickingPalletWithUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.AddPickingPalletWithUser_Result> AddPickingPalletWithUserAsync(string sSCC, string orderNo, int lineNo, decimal qty, string user) {
            ScanCongel.ScanCU.AddPickingPalletWithUser inValue = new ScanCongel.ScanCU.AddPickingPalletWithUser();
            inValue.sSCC = sSCC;
            inValue.orderNo = orderNo;
            inValue.lineNo = lineNo;
            inValue.qty = qty;
            inValue.user = user;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).AddPickingPalletWithUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.ValidatePicking_Result ScanCongel.ScanCU.Scan_Port.ValidatePicking(ScanCongel.ScanCU.ValidatePicking request) {
            return base.Channel.ValidatePicking(request);
        }
        
        public void ValidatePicking(string orderNo) {
            ScanCongel.ScanCU.ValidatePicking inValue = new ScanCongel.ScanCU.ValidatePicking();
            inValue.orderNo = orderNo;
            ScanCongel.ScanCU.ValidatePicking_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePicking(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePicking_Result> ScanCongel.ScanCU.Scan_Port.ValidatePickingAsync(ScanCongel.ScanCU.ValidatePicking request) {
            return base.Channel.ValidatePickingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePicking_Result> ValidatePickingAsync(string orderNo) {
            ScanCongel.ScanCU.ValidatePicking inValue = new ScanCongel.ScanCU.ValidatePicking();
            inValue.orderNo = orderNo;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePickingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.ValidatePickingWithUser_Result ScanCongel.ScanCU.Scan_Port.ValidatePickingWithUser(ScanCongel.ScanCU.ValidatePickingWithUser request) {
            return base.Channel.ValidatePickingWithUser(request);
        }
        
        public void ValidatePickingWithUser(string orderNo, string user) {
            ScanCongel.ScanCU.ValidatePickingWithUser inValue = new ScanCongel.ScanCU.ValidatePickingWithUser();
            inValue.orderNo = orderNo;
            inValue.user = user;
            ScanCongel.ScanCU.ValidatePickingWithUser_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePickingWithUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePickingWithUser_Result> ScanCongel.ScanCU.Scan_Port.ValidatePickingWithUserAsync(ScanCongel.ScanCU.ValidatePickingWithUser request) {
            return base.Channel.ValidatePickingWithUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePickingWithUser_Result> ValidatePickingWithUserAsync(string orderNo, string user) {
            ScanCongel.ScanCU.ValidatePickingWithUser inValue = new ScanCongel.ScanCU.ValidatePickingWithUser();
            inValue.orderNo = orderNo;
            inValue.user = user;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePickingWithUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.ValidatePurchOrder_Result ScanCongel.ScanCU.Scan_Port.ValidatePurchOrder(ScanCongel.ScanCU.ValidatePurchOrder request) {
            return base.Channel.ValidatePurchOrder(request);
        }
        
        public string ValidatePurchOrder(string cmd, string expectedReceiptDt, string magasin) {
            ScanCongel.ScanCU.ValidatePurchOrder inValue = new ScanCongel.ScanCU.ValidatePurchOrder();
            inValue.cmd = cmd;
            inValue.expectedReceiptDt = expectedReceiptDt;
            inValue.magasin = magasin;
            ScanCongel.ScanCU.ValidatePurchOrder_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePurchOrder(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePurchOrder_Result> ScanCongel.ScanCU.Scan_Port.ValidatePurchOrderAsync(ScanCongel.ScanCU.ValidatePurchOrder request) {
            return base.Channel.ValidatePurchOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePurchOrder_Result> ValidatePurchOrderAsync(string cmd, string expectedReceiptDt, string magasin) {
            ScanCongel.ScanCU.ValidatePurchOrder inValue = new ScanCongel.ScanCU.ValidatePurchOrder();
            inValue.cmd = cmd;
            inValue.expectedReceiptDt = expectedReceiptDt;
            inValue.magasin = magasin;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePurchOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result ScanCongel.ScanCU.Scan_Port.MakeOTSFromPurchOrder(ScanCongel.ScanCU.MakeOTSFromPurchOrder request) {
            return base.Channel.MakeOTSFromPurchOrder(request);
        }
        
        public void MakeOTSFromPurchOrder(string cmd, string expectedReceiptDt, string magasin) {
            ScanCongel.ScanCU.MakeOTSFromPurchOrder inValue = new ScanCongel.ScanCU.MakeOTSFromPurchOrder();
            inValue.cmd = cmd;
            inValue.expectedReceiptDt = expectedReceiptDt;
            inValue.magasin = magasin;
            ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).MakeOTSFromPurchOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result> ScanCongel.ScanCU.Scan_Port.MakeOTSFromPurchOrderAsync(ScanCongel.ScanCU.MakeOTSFromPurchOrder request) {
            return base.Channel.MakeOTSFromPurchOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.MakeOTSFromPurchOrder_Result> MakeOTSFromPurchOrderAsync(string cmd, string expectedReceiptDt, string magasin) {
            ScanCongel.ScanCU.MakeOTSFromPurchOrder inValue = new ScanCongel.ScanCU.MakeOTSFromPurchOrder();
            inValue.cmd = cmd;
            inValue.expectedReceiptDt = expectedReceiptDt;
            inValue.magasin = magasin;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).MakeOTSFromPurchOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PrintLabel_Result ScanCongel.ScanCU.Scan_Port.PrintLabel(ScanCongel.ScanCU.PrintLabel request) {
            return base.Channel.PrintLabel(request);
        }
        
        public void PrintLabel(string sSCCNo) {
            ScanCongel.ScanCU.PrintLabel inValue = new ScanCongel.ScanCU.PrintLabel();
            inValue.sSCCNo = sSCCNo;
            ScanCongel.ScanCU.PrintLabel_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PrintLabel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintLabel_Result> ScanCongel.ScanCU.Scan_Port.PrintLabelAsync(ScanCongel.ScanCU.PrintLabel request) {
            return base.Channel.PrintLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintLabel_Result> PrintLabelAsync(string sSCCNo) {
            ScanCongel.ScanCU.PrintLabel inValue = new ScanCongel.ScanCU.PrintLabel();
            inValue.sSCCNo = sSCCNo;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PrintLabelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PrintReceipt_Result ScanCongel.ScanCU.Scan_Port.PrintReceipt(ScanCongel.ScanCU.PrintReceipt request) {
            return base.Channel.PrintReceipt(request);
        }
        
        public void PrintReceipt(string receive, string quai) {
            ScanCongel.ScanCU.PrintReceipt inValue = new ScanCongel.ScanCU.PrintReceipt();
            inValue.receive = receive;
            inValue.quai = quai;
            ScanCongel.ScanCU.PrintReceipt_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PrintReceipt(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintReceipt_Result> ScanCongel.ScanCU.Scan_Port.PrintReceiptAsync(ScanCongel.ScanCU.PrintReceipt request) {
            return base.Channel.PrintReceiptAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintReceipt_Result> PrintReceiptAsync(string receive, string quai) {
            ScanCongel.ScanCU.PrintReceipt inValue = new ScanCongel.ScanCU.PrintReceipt();
            inValue.receive = receive;
            inValue.quai = quai;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PrintReceiptAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PrintFichePaletteProduction_Result ScanCongel.ScanCU.Scan_Port.PrintFichePaletteProduction(ScanCongel.ScanCU.PrintFichePaletteProduction request) {
            return base.Channel.PrintFichePaletteProduction(request);
        }
        
        public void PrintFichePaletteProduction(string sSCC) {
            ScanCongel.ScanCU.PrintFichePaletteProduction inValue = new ScanCongel.ScanCU.PrintFichePaletteProduction();
            inValue.sSCC = sSCC;
            ScanCongel.ScanCU.PrintFichePaletteProduction_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PrintFichePaletteProduction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintFichePaletteProduction_Result> ScanCongel.ScanCU.Scan_Port.PrintFichePaletteProductionAsync(ScanCongel.ScanCU.PrintFichePaletteProduction request) {
            return base.Channel.PrintFichePaletteProductionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PrintFichePaletteProduction_Result> PrintFichePaletteProductionAsync(string sSCC) {
            ScanCongel.ScanCU.PrintFichePaletteProduction inValue = new ScanCongel.ScanCU.PrintFichePaletteProduction();
            inValue.sSCC = sSCC;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PrintFichePaletteProductionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.ValidatePaletteProduction_Result ScanCongel.ScanCU.Scan_Port.ValidatePaletteProduction(ScanCongel.ScanCU.ValidatePaletteProduction request) {
            return base.Channel.ValidatePaletteProduction(request);
        }
        
        public void ValidatePaletteProduction(string sSCC) {
            ScanCongel.ScanCU.ValidatePaletteProduction inValue = new ScanCongel.ScanCU.ValidatePaletteProduction();
            inValue.sSCC = sSCC;
            ScanCongel.ScanCU.ValidatePaletteProduction_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePaletteProduction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePaletteProduction_Result> ScanCongel.ScanCU.Scan_Port.ValidatePaletteProductionAsync(ScanCongel.ScanCU.ValidatePaletteProduction request) {
            return base.Channel.ValidatePaletteProductionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.ValidatePaletteProduction_Result> ValidatePaletteProductionAsync(string sSCC) {
            ScanCongel.ScanCU.ValidatePaletteProduction inValue = new ScanCongel.ScanCU.ValidatePaletteProduction();
            inValue.sSCC = sSCC;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).ValidatePaletteProductionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.TftFromProdToCongel_Result ScanCongel.ScanCU.Scan_Port.TftFromProdToCongel(ScanCongel.ScanCU.TftFromProdToCongel request) {
            return base.Channel.TftFromProdToCongel(request);
        }
        
        public void TftFromProdToCongel(string sSCC) {
            ScanCongel.ScanCU.TftFromProdToCongel inValue = new ScanCongel.ScanCU.TftFromProdToCongel();
            inValue.sSCC = sSCC;
            ScanCongel.ScanCU.TftFromProdToCongel_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).TftFromProdToCongel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.TftFromProdToCongel_Result> ScanCongel.ScanCU.Scan_Port.TftFromProdToCongelAsync(ScanCongel.ScanCU.TftFromProdToCongel request) {
            return base.Channel.TftFromProdToCongelAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.TftFromProdToCongel_Result> TftFromProdToCongelAsync(string sSCC) {
            ScanCongel.ScanCU.TftFromProdToCongel inValue = new ScanCongel.ScanCU.TftFromProdToCongel();
            inValue.sSCC = sSCC;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).TftFromProdToCongelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.ScanCU.PalletInventory_Result ScanCongel.ScanCU.Scan_Port.PalletInventory(ScanCongel.ScanCU.PalletInventory request) {
            return base.Channel.PalletInventory(request);
        }
        
        public void PalletInventory(string sSCC, decimal newQuantity, string user) {
            ScanCongel.ScanCU.PalletInventory inValue = new ScanCongel.ScanCU.PalletInventory();
            inValue.sSCC = sSCC;
            inValue.newQuantity = newQuantity;
            inValue.user = user;
            ScanCongel.ScanCU.PalletInventory_Result retVal = ((ScanCongel.ScanCU.Scan_Port)(this)).PalletInventory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.ScanCU.PalletInventory_Result> ScanCongel.ScanCU.Scan_Port.PalletInventoryAsync(ScanCongel.ScanCU.PalletInventory request) {
            return base.Channel.PalletInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.ScanCU.PalletInventory_Result> PalletInventoryAsync(string sSCC, decimal newQuantity, string user) {
            ScanCongel.ScanCU.PalletInventory inValue = new ScanCongel.ScanCU.PalletInventory();
            inValue.sSCC = sSCC;
            inValue.newQuantity = newQuantity;
            inValue.user = user;
            return ((ScanCongel.ScanCU.Scan_Port)(this)).PalletInventoryAsync(inValue);
        }
    }
}
