//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanCongel.NAVUsers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", ConfigurationName="NAVUsers.Users_Port")]
    public interface Users_Port {
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Read_Result) du message Read_Result ne correspond pas à la valeur par défaut (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.Read_Result Read(ScanCongel.NAVUsers.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Read_Result> ReadAsync(ScanCongel.NAVUsers.Read request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadByRecId_Result) du message ReadByRecId_Result ne correspond pas à la valeur par défaut (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.ReadByRecId_Result ReadByRecId(ScanCongel.NAVUsers.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadByRecId_Result> ReadByRecIdAsync(ScanCongel.NAVUsers.ReadByRecId request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ReadMultiple_Result) du message ReadMultiple_Result ne correspond pas à la valeur par défaut (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.ReadMultiple_Result ReadMultiple(ScanCongel.NAVUsers.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.NAVUsers.ReadMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (IsUpdated_Result) du message IsUpdated_Result ne correspond pas à la valeur par défaut (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.IsUpdated_Result IsUpdated(ScanCongel.NAVUsers.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.IsUpdated_Result> IsUpdatedAsync(ScanCongel.NAVUsers.IsUpdated request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (GetRecIdFromKey_Result) du message GetRecIdFromKey_Result ne correspond pas à la valeur par défaut (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.GetRecIdFromKey_Result GetRecIdFromKey(ScanCongel.NAVUsers.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(ScanCongel.NAVUsers.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.Create_Result Create(ScanCongel.NAVUsers.Create request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Create_Result> CreateAsync(ScanCongel.NAVUsers.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.CreateMultiple_Result CreateMultiple(ScanCongel.NAVUsers.CreateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.NAVUsers.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.Update_Result Update(ScanCongel.NAVUsers.Update request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Update_Result> UpdateAsync(ScanCongel.NAVUsers.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.UpdateMultiple_Result UpdateMultiple(ScanCongel.NAVUsers.UpdateMultiple request);
        
        // CODEGEN : Génération du contrat de message dans la mesure où l'opération compte plusieurs valeurs de retour.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.NAVUsers.UpdateMultiple request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (Delete_Result) du message Delete_Result ne correspond pas à la valeur par défaut (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ScanCongel.NAVUsers.Delete_Result Delete(ScanCongel.NAVUsers.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/users:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Delete_Result> DeleteAsync(ScanCongel.NAVUsers.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users")]
    public partial class Users : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string first_NameField;
        
        private string last_NameField;
        
        private string userField;
        
        private bool inventoryScanField;
        
        private bool inventoryScanFieldSpecified;
        
        private string barcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string First_Name {
            get {
                return this.first_NameField;
            }
            set {
                this.first_NameField = value;
                this.RaisePropertyChanged("First_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Last_Name {
            get {
                return this.last_NameField;
            }
            set {
                this.last_NameField = value;
                this.RaisePropertyChanged("Last_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool InventoryScan {
            get {
                return this.inventoryScanField;
            }
            set {
                this.inventoryScanField = value;
                this.RaisePropertyChanged("InventoryScan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryScanSpecified {
            get {
                return this.inventoryScanFieldSpecified;
            }
            set {
                this.inventoryScanFieldSpecified = value;
                this.RaisePropertyChanged("InventoryScanSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("Barcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users")]
    public partial class Users_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Users_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Users_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users")]
    public enum Users_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        First_Name,
        
        /// <remarks/>
        Last_Name,
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        InventoryScan,
        
        /// <remarks/>
        Barcode,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public Read_Result() {
        }
        
        public Read_Result(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public ScanCongel.NAVUsers.Users_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(ScanCongel.NAVUsers.Users_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.NAVUsers.Users[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(ScanCongel.NAVUsers.Users[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public Create() {
        }
        
        public Create(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public Create_Result() {
        }
        
        public Create_Result(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.NAVUsers.Users[] Users_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(ScanCongel.NAVUsers.Users[] Users_List) {
            this.Users_List = Users_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.NAVUsers.Users[] Users_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(ScanCongel.NAVUsers.Users[] Users_List) {
            this.Users_List = Users_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public Update() {
        }
        
        public Update(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public ScanCongel.NAVUsers.Users Users;
        
        public Update_Result() {
        }
        
        public Update_Result(ScanCongel.NAVUsers.Users Users) {
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.NAVUsers.Users[] Users_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(ScanCongel.NAVUsers.Users[] Users_List) {
            this.Users_List = Users_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ScanCongel.NAVUsers.Users[] Users_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(ScanCongel.NAVUsers.Users[] Users_List) {
            this.Users_List = Users_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/users", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/users", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Users_PortChannel : ScanCongel.NAVUsers.Users_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Users_PortClient : System.ServiceModel.ClientBase<ScanCongel.NAVUsers.Users_Port>, ScanCongel.NAVUsers.Users_Port {
        
        public Users_PortClient() {
        }
        
        public Users_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Users_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Users_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Users_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.Read_Result ScanCongel.NAVUsers.Users_Port.Read(ScanCongel.NAVUsers.Read request) {
            return base.Channel.Read(request);
        }
        
        public ScanCongel.NAVUsers.Users Read(string No) {
            ScanCongel.NAVUsers.Read inValue = new ScanCongel.NAVUsers.Read();
            inValue.No = No;
            ScanCongel.NAVUsers.Read_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).Read(inValue);
            return retVal.Users;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Read_Result> ScanCongel.NAVUsers.Users_Port.ReadAsync(ScanCongel.NAVUsers.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.Read_Result> ReadAsync(string No) {
            ScanCongel.NAVUsers.Read inValue = new ScanCongel.NAVUsers.Read();
            inValue.No = No;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.ReadByRecId_Result ScanCongel.NAVUsers.Users_Port.ReadByRecId(ScanCongel.NAVUsers.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public ScanCongel.NAVUsers.Users ReadByRecId(string recId) {
            ScanCongel.NAVUsers.ReadByRecId inValue = new ScanCongel.NAVUsers.ReadByRecId();
            inValue.recId = recId;
            ScanCongel.NAVUsers.ReadByRecId_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).ReadByRecId(inValue);
            return retVal.Users;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadByRecId_Result> ScanCongel.NAVUsers.Users_Port.ReadByRecIdAsync(ScanCongel.NAVUsers.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            ScanCongel.NAVUsers.ReadByRecId inValue = new ScanCongel.NAVUsers.ReadByRecId();
            inValue.recId = recId;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.ReadMultiple_Result ScanCongel.NAVUsers.Users_Port.ReadMultiple(ScanCongel.NAVUsers.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public ScanCongel.NAVUsers.Users[] ReadMultiple(ScanCongel.NAVUsers.Users_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.NAVUsers.ReadMultiple inValue = new ScanCongel.NAVUsers.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            ScanCongel.NAVUsers.ReadMultiple_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadMultiple_Result> ScanCongel.NAVUsers.Users_Port.ReadMultipleAsync(ScanCongel.NAVUsers.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.ReadMultiple_Result> ReadMultipleAsync(ScanCongel.NAVUsers.Users_Filter[] filter, string bookmarkKey, int setSize) {
            ScanCongel.NAVUsers.ReadMultiple inValue = new ScanCongel.NAVUsers.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.IsUpdated_Result ScanCongel.NAVUsers.Users_Port.IsUpdated(ScanCongel.NAVUsers.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            ScanCongel.NAVUsers.IsUpdated inValue = new ScanCongel.NAVUsers.IsUpdated();
            inValue.Key = Key;
            ScanCongel.NAVUsers.IsUpdated_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.IsUpdated_Result> ScanCongel.NAVUsers.Users_Port.IsUpdatedAsync(ScanCongel.NAVUsers.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.IsUpdated_Result> IsUpdatedAsync(string Key) {
            ScanCongel.NAVUsers.IsUpdated inValue = new ScanCongel.NAVUsers.IsUpdated();
            inValue.Key = Key;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.GetRecIdFromKey_Result ScanCongel.NAVUsers.Users_Port.GetRecIdFromKey(ScanCongel.NAVUsers.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            ScanCongel.NAVUsers.GetRecIdFromKey inValue = new ScanCongel.NAVUsers.GetRecIdFromKey();
            inValue.Key = Key;
            ScanCongel.NAVUsers.GetRecIdFromKey_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.GetRecIdFromKey_Result> ScanCongel.NAVUsers.Users_Port.GetRecIdFromKeyAsync(ScanCongel.NAVUsers.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            ScanCongel.NAVUsers.GetRecIdFromKey inValue = new ScanCongel.NAVUsers.GetRecIdFromKey();
            inValue.Key = Key;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.Create_Result ScanCongel.NAVUsers.Users_Port.Create(ScanCongel.NAVUsers.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref ScanCongel.NAVUsers.Users Users) {
            ScanCongel.NAVUsers.Create inValue = new ScanCongel.NAVUsers.Create();
            inValue.Users = Users;
            ScanCongel.NAVUsers.Create_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).Create(inValue);
            Users = retVal.Users;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.Create_Result> CreateAsync(ScanCongel.NAVUsers.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.CreateMultiple_Result ScanCongel.NAVUsers.Users_Port.CreateMultiple(ScanCongel.NAVUsers.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref ScanCongel.NAVUsers.Users[] Users_List) {
            ScanCongel.NAVUsers.CreateMultiple inValue = new ScanCongel.NAVUsers.CreateMultiple();
            inValue.Users_List = Users_List;
            ScanCongel.NAVUsers.CreateMultiple_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).CreateMultiple(inValue);
            Users_List = retVal.Users_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.CreateMultiple_Result> CreateMultipleAsync(ScanCongel.NAVUsers.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.Update_Result ScanCongel.NAVUsers.Users_Port.Update(ScanCongel.NAVUsers.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref ScanCongel.NAVUsers.Users Users) {
            ScanCongel.NAVUsers.Update inValue = new ScanCongel.NAVUsers.Update();
            inValue.Users = Users;
            ScanCongel.NAVUsers.Update_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).Update(inValue);
            Users = retVal.Users;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.Update_Result> UpdateAsync(ScanCongel.NAVUsers.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.UpdateMultiple_Result ScanCongel.NAVUsers.Users_Port.UpdateMultiple(ScanCongel.NAVUsers.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref ScanCongel.NAVUsers.Users[] Users_List) {
            ScanCongel.NAVUsers.UpdateMultiple inValue = new ScanCongel.NAVUsers.UpdateMultiple();
            inValue.Users_List = Users_List;
            ScanCongel.NAVUsers.UpdateMultiple_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).UpdateMultiple(inValue);
            Users_List = retVal.Users_List;
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.UpdateMultiple_Result> UpdateMultipleAsync(ScanCongel.NAVUsers.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ScanCongel.NAVUsers.Delete_Result ScanCongel.NAVUsers.Users_Port.Delete(ScanCongel.NAVUsers.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            ScanCongel.NAVUsers.Delete inValue = new ScanCongel.NAVUsers.Delete();
            inValue.Key = Key;
            ScanCongel.NAVUsers.Delete_Result retVal = ((ScanCongel.NAVUsers.Users_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ScanCongel.NAVUsers.Delete_Result> ScanCongel.NAVUsers.Users_Port.DeleteAsync(ScanCongel.NAVUsers.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ScanCongel.NAVUsers.Delete_Result> DeleteAsync(string Key) {
            ScanCongel.NAVUsers.Delete inValue = new ScanCongel.NAVUsers.Delete();
            inValue.Key = Key;
            return ((ScanCongel.NAVUsers.Users_Port)(this)).DeleteAsync(inValue);
        }
    }
}
